categories:
- Text Manipulation
description: High performance text processing tools using the GNU coreutils, sed, awk and friends.
homepage_url: https://www.gnu.org/software/
long_description: |
  That repository contains all kind of different text processing tools.

    * awk - The AWK programmning language ( http://www.gnu.org/software/gawk/ )
    * sed - Stream Editor ( https://www.gnu.org/software/sed/ )
    * grep - Search files ( http://www.gnu.org/software/grep/ )
    * sort_columns - Sorting every line according to there columns
    * GNU Coreutils programs ( http://www.gnu.org/software/coreutils/ ):
    * sort - sort files * join - join two files, based on common key field.
    * cut - keep/discard fields from a file * unsorted_uniq - keep unique/duplicated lines in a file
    * sorted_uniq - keep unique/duplicated lines in a file * head - keep the first X lines in a file
    * tail - keep the last X lines in a file

    Originally known as "Unix Tools" and developed from Assaf Gordon @ Greg Hannon's lab ( http://hannonlab.cshl.edu )
    in Cold Spring Harbor Laboratory, it is now hosted under https://github.com/bgruening/galaxytools/tree/master/tools/text_processing
    and open for contributions. It will also replace several smaller sed, sort and uniq wrappers, developed over the time.
    Repository-Maintainer: Björn Grüning
name: text_processing
owner: bgruening
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/text_processing/text_processing
type: unrestricted
