name: package_python_bioformats_1_0_4
owner: iuc
description: Contains a tool dependency definition that downloads and extracts version
  1.0.4 of Python-bioformats.
homepage_url: https://pypi.python.org/pypi/python-bioformats
long_description: |
  Python-bioformats is a Python wrapper for Bio-Formats, a stand-alone Java library for
  reading and writing life sciences image file formats. Bio-Formats is capable of parsing
  both pixels and metadata for a large number of formats, as well as writing to several
  formats.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/packages/package_python_bioformats_1_0_4
type: tool_dependency_definition
categories:
  - Tool Dependency Packages
