name: My oscar report
datasets:
  oscars:
    path: oscars.csv
    offer-excel: true
    links:
      link to oscar plot:
        column: age
        view: oscar-plot
      link to movie:
        column: movie
        table-row: movies/Title
  movies:
    path: movies.csv
    offer-excel: true
    links:
      link to oscar entry:
        column: Title
        table-row: oscars/movie
views:
  oscars:
    dataset: oscars
    desc: |
      ## All winning oscars beginning in the year 1929.
      This table contains *all* winning oscars for best actress and best actor.
    page-size: 25
    render-table:
      columns:
        index(0):
          display-mode: hidden
        oscar_yr:
          label: year
        age:
          plot:
            ticks:
              scale: linear
              domain:
                - 20
                - 100
        name:
          link-to-url:
            lmgtfy:
              url: "https://www.google.com/search?q={name}"
        movie:
          link-to-url:
            Wikipedia:
              url: "https://en.wikipedia.org/wiki/{value}"
        award:
          plot:
            heatmap:
              scale: ordinal
              domain:
                - Best actor
                - Best actress
              range:
                - "#add8e6"
                - "#ffb6c1"
              legend:
                title: award
  oscar-plot:
    dataset: oscars
    desc: |
      ### My beautiful oscar scatter plot
    render-plot:
      spec: |
        {
          "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
          "description": "A scatterplot showing oscars.",
          "mark": {
            "type": "point",
            "tooltip": {
              "content": "data"
            }
          },
          "encoding": {
            "x": {
              "field": "oscar_yr",
              "type": "quantitative",
              "scale": {
                "zero": false
              }
            },
            "y": {
              "field": "age",
              "type": "quantitative",
              "scale": {
                "zero": false
              }
            },
            "color": {
              "field": "award",
              "type": "nominal"
            }
          }
        }
  movies:
    dataset: movies
    render-table:
      columns:
        Director:
          ellipsis: 40
        Genre:
          plot:
            pills:
              separator: ","
              color-scheme: category20
        imdbID:
          link-to-url:
            IMDB:
              url: "https://www.imdb.com/title/{value}/"
        Title:
          link-to-url:
            Wikipedia:
              url: "https://en.wikipedia.org/wiki/{value}"
        imdbRating:
          precision: 1
          plot:
            bars:
              scale: linear
              domain:
                - 1
                - 10
              color:
                scale: linear
                range:
                  - red
                  - green
        Rated:
          plot-view-legend: true
          plot:
            heatmap:
              scale: ordinal
              color-scheme: tableau20
              legend:
                title: Rating
