name: cellposesam
owner: bgruening
categories:
  - Imaging
description: CellPose SAM
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for CellPoseSAM {{ tool_name }}."

