name: cellposesam
owner: bgruening
categories:
  - Imaging
description: CellPose SAM
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools
type: unrestricted
homepage_url: https://cellpose.org
long_description: |
    Cellpose-SAM: cell and nucleus segmentation with superhuman generalization. It can be optimized for your own data, applied in 3D, works on images with shot noise, (an)isotropic blur, undersampling, contrast inversions, regardless of channel order and object sizes.
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for CellPoseSAM {{ tool_name }}."

