categories:
- Computational chemistry
description: Similarity Search for chemical molecules (chemfp)
long_description: |
  chemfp is a set of command-lines tools for generating cheminformatics fingerprints and searching those fingerprints by Tanimoto similarity
  
  Home page: http://chemfp.readthedocs.io
  License: MIT

homepage_url: http://chemfp.readthedocs.io
name: simsearch
owner: bgruening
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/chemicaltoolbox/simsearch
type: unrestricted
maintainers:
  - simonbray
