name: imagej2_convert_format
owner: iuc
description: Contains a tool that converts the format of an input image file, producing an output image
  file of the selected format.
homepage_url:
long_description:
remote_repository_url:
type: unrestricted
categories:
- Imaging
