name: unique
owner: bgruening
description: This tool returns all unique lines from a tab-separated file.
homepage_url: https://github.com/bgruening/galaxytools/tree/master/tools/file_manipulation
long_description: This tool returns all unique lines from a tab-separated file.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/file_manipulation
type: unrestricted
categories:
- Text Manipulation
