name: selectsequencesfrommsa
owner: rnateam
description: SelectSequences - selects representative entries from a multiple sequence alignment in clustal format
homepage_url: https://github.com/eggzilla/SelectSequences
long_description: |
 Tool to select representative sequences from a multiple sequence alignment in clustal format.
 Useful before running RNAz, RNAcode, RNAalifold on alignments with many entries. 
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/rna_tools/selectsequencesfrommsa
type: unrestricted
categories:
  - RNA
  - Sequence Analysis
