name: run_jupyter_job
owner: bgruening
description: Run jupyter notebook script in Galaxy

long_description: |
  Run jupyter notebook script in Galaxy.

categories:
  - Machine Learning
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/jupyter_job
