name: gpt
description: Using the OpenAI GPT-3 model to generate text.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/gpt
homepage_url: https://github.com/bgruening/galaxytools/tree/master/tools/gpt
type:
categories:
  - Machine Learning
maintainers:
  - arash77
