name: imagej2_watershed_binary
owner: iuc
description: |
  Contains a tool that wraps the ImageJ2 Watershed command for binary images.
homepage_url: http://rsbweb.nih.gov/ij/docs/guide/146-29.html
long_description: |
  Watershed segmentation is a way of automatically separating or cutting apart
  particles that touch.
remote_repository_url:
type: unrestricted
categories:
- Imaging
