name: kraken_ocr
owner: bgruening
description: Wrapper of the OCR system kraken
long_description: |
  kraken is a turn-key OCR system optimized for historical and non-Latin script material.
type: unrestricted
# took the same category as tools-iuc/tesseract
categories:
  - Natural Language Processing
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/kraken_ocr
homepage_url: https://kraken.re/
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for HTR/OCR tool: {{ tool_name }}"
suite:
  name: "suite_kraken_ocr"
  description: Wrapper of the OCR System kraken
  long_description: |
    kraken is a turn-key OCR system optimized for historical and non-Latin script material.