owner: todo 
name: split_file_to_collection
categories: 
  - Text Manipulation
description: Split tabular, MGF, FASTA, or FASTQ files to a dataset collection. 
remote_repository_url: ???
type: unrestricted
