name: rnacommender
owner: rnateam
description: RNAcommender is a tool for genome-wide recommendation of RNA-protein interactions.
homepage_url: https://github.com/gianlucacorrado/RNAcommender.git
long_description: RNAcommender is a tool for genome-wide recommendation of RNA-protein interactions. It is a recommender system capable of suggesting RNA targets to unexplored RNA binding proteins, by propagating the available interaction information, taking into account the protein domain composition and the RNA predicted secondary structure.
remote_repository_url:https://github.com/gianlucacorrado/RNAcommender.git
type: unrestricted
categories:
- RNA
