name: music
owner: bgruening
description: "Multi-subject Single Cell deconvolution (MuSiC)"
homepage_url: https://github.com/xuranw/MuSiC
long_description: |
    MuSiC is a deconvolution method that utilizes cross-subject scRNA-seq to estimate cell type proportions in bulk RNA-seq data.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/music_deconvolution
type: unrestricted
categories:
- Transcriptomics
- Single Cell
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for the MuSiC tool suite: {{ tool_name }}"
suite:
  name: "suite_music"
  description: "Multi-subject Single Cell deconvolution (MuSiC)"
  long_description: |
    MuSiC is a deconvolution method that utilizes cross-subject scRNA-seq to estimate cell type proportions in bulk RNA-seq data.
