name: join_files_on_column_fuzzy
owner: bgruening
description: Join two files on a common column, allowing a certain difference.
long_description: |
    Join two files on a common column. You can provide the allowed difference between both values (currently only numbers)
    as the absolute differece or as PPM.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/text_processing/join_files_on_column_fuzzy
type: unrestricted
categories:
- Text Manipulation
