categories:
- RNA
description: Multiple alignment program for amino acid or nucleotide sequences
long_description: |
    MAFFT is a multiple sequence alignment program for unix-like operating systems.  
    It offers a range of multiple alignment methods, L-INS-i (accurate; for alignment of <∼200 sequences), 
    FFT-NS-2 (fast; for alignment of <∼30,000 sequences), etc.
name: mafft
owner: rnateam
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/mafft
type: unrestricted
