name: xchem_transfs_scoring
owner: bgruening
remote_repository_url: "https://github.com/bgruening/galaxytools/tree/master/chemicaltoolbox/xchem-deep"
homepage_url: "https://github.com/bgruening/galaxytools/tree/master/chemicaltoolbox/xchem-deep"
categories:
- Computational chemistry
description: "This tool performs scoring of docked ligand poses using deep learning."
long_description: |
  This tool performs scoring of docked ligand poses using deep learning.
  It uses the gnina and libmolgrid toolkits to perform the scoring to generate
  a prediction for how good the pose is.
type: unrestricted