name: bioimage_inference
owner: bgruening
description: "Load model from BioImage.IO and make inferences"
homepage_url: https://github.com/bgruening/galaxytools
long_description: 
    Load model from BioImage.IO and make inferences
remote_repository_url: https://github.com/bgruening/galaxytools/tree/recommendation_training/tools/bioimaging
type: unrestricted
categories:
- Imaging

