name: grobid_dataset_annotate
owner: iuc
description: Identify dataset mentions in scientific articles with DataStet
long_description: |
  Galaxy wrapper for the GROBID DataStet service. The tool starts the DataStet
  web service inside the job container and annotates dataset mentions in PDF or
  TEI scientific articles.
homepage_url: https://github.com/kermitt2/datastet
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/grobid_dataset_annotate
type: unrestricted
categories:
  - Text Manipulation
  - Natural Language Processing
