name: sortmerna
owner: rnateam
description: SortMeRNA is a software designed to rapidly filter ribosomal RNA fragments from metatransriptomic data produced by next-generation sequencers.
homepage_url: http://bioinfo.lifl.fr/RNA/sortmerna/
long_description: SortMeRNA_ is a software designed to rapidly filter ribosomal RNA fragments from metatransriptomic data produced by next-generation sequencers. It is capable of handling large RNA databases and sorting out all fragments matching to the database with high accuracy and specificity. http://bioinfo.lifl.fr/RNA/sortmerna/
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/rna_tools/sortmerna
type: unrestricted
categories:
- RNA
