categories:
- RNA
- Statistics
description: Differential DNA methylation calling
long-description: |
    Fast and sensitive calling of differentially methylated DNA regions from
    bisulfite sequencing data
name: metilene
owner: rnateam
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/metilene
type: unrestricted
