categories:
- Computational chemistry
description: Software for protein-compound docking - the prepare receptor step
long_description: |
    AutoDock Vina is an open-source program for doing molecular docking.
name: autodock_vina_prepare_receptor
owner: bgruening
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/chemicaltoolbox/autodock_vina
type: unrestricted
