name: proteinortho
owner: bgruening
description: Detect orthologous genes within different species
homepage_url: https://www.bioinf.uni-leipzig.de/Software/proteinortho/
long_description: |
    Proteinortho is a tool to detect orthologous genes within different species. 
    For doing so, it compares similarities of given gene sequences and clusters 
    them to find significant groups. The algorithm was designed to handle large
    -scale data and can be applied to hundreds of species at one. To enhance the 
    prediction accuracy, the relative order of genes (synteny) can be used as 
    additional feature for the discrimination of orthologs. 
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/pileometh
type: unrestricted
categories:
- Sequence Analysis
