categories:
- Computational chemistry
description: Shape-it is a tool that aligns a reference molecule against a set of database molecules
long_description: |
    Shape-it is a tool that aligns a reference molecule against a set of database
    molecules using the shape of the molecules as the align criterion.
    It is based on the use of `gaussian volumes as descriptor for molecular shape`_ as it was introduced by Grant and Pickup.

    Home page: http://silicos-it.be.s3-website-eu-west-1.amazonaws.com/software/shape-it/1.0.1/shape-it.html
    License: GPL3+

name: shape_it
owner: bgruening
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/chemicaltoolbox/silicos-it/shape-it
type: unrestricted
