name: pipmir
owner: rnateam
description: A method to identify novel plant miRNA.
homepage_url: https://ohlerlab.mdc-berlin.de/software/Pipeline_for_the_Identification_of_Plant_miRNAs_84/
long_description: |
    We developed the PIPmiR algorithm to identify novel plant miRNA
    genes from a combination of deep sequencing data and genomic features.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/rna_tools/pipmir
type: unrestricted
categories:
- RNA
