categories:
  - Imaging
description: Binary 2 label image
long_description: This tools converts a binary image to a label image (every object has an own grey value).
name: binary2labelimage
owner: thomaswollmann
homepage_url: https://github.com/bmcv
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tools/\binary2labelimage
