name: biomodels
owner: bgruening
categories:
  - Machine Learning
description: Wrappers for tools to bring BioModels AI models into Galaxy.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for {{ tool_name }} from BioModels."
suite:
  name: "suite_biomodels"
  description: "A suite of tools that brings the BioModels AI models into Galaxy."
  long_description: |
      BioModels is a repository of mathematical models of biological and biomedical systems.
