name: biomodel_BIOMD0000001066
owner: bgruening
description: Random Forest model to predict efficacy of immune checkpoint blockade across multiple cancer patient cohorts

long_description: |
  Random Forest model to predict efficacy of immune checkpoint blockade across multiple cancer patient cohorts.
  The official repository is at https://www.ebi.ac.uk/biomodels/BIOMD0000001066

categories:
  - Machine Learning
  - Trained models
  - Random Forest
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/biomodelsML
homepage_url: https://www.ebi.ac.uk/biomodels/BIOMD0000001066
