name: imagej2_bunwarpj_compare_elastic_raw
owner: iuc
description: |
  Contains a tool that wraps the bUnwarpJ ImageJ2 plugin, restricting use to the
  "-compare_elastic_raw" option when running bUnwarpJ from the command line.
homepage_url: http://biocomp.cnb.csic.es/~iarganda/bUnwarpJ/
long_description: |
  Calculates the warping index of an elastic transformation and a raw transformation. The elastic
  transformation file must be in the same format as the files created with the Save transformation
  option of the Align two images with bUnwarpJ tool, while the raw transformation file must be
  in the same format as the file produced by the Convert elastic transformation to raw with bUnwarpJ
  tool.
remote_repository_url:
type: unrestricted
categories:
- Imaging
