name: imagej2_bunwarpj_align
owner: iuc
description: |
  Contains a tool that wraps the bUnwarpJ ImageJ2 plugin, restricting use to the
  "-align" option when running bUnwarpJ from the command line.
homepage_url: http://biocomp.cnb.csic.es/~iarganda/bUnwarpJ/
long_description: |
  Performs a simultaneous registration of two images, A and B. Image A is elastically deformed
  in order to look as similar as possible to image B, and, at the same time, the "inverse"
  transformation (from B to A) is also calculated so a pseudo-invertibility of the final deformation
  could be guaranteed.  Two images are produced: the deformed versions of A and B images.
  remote_repository_url:
type: unrestricted
categories:
- Imaging
