name: 3dtrees_py3dtiles
owner: bgruening
description: generates 3D tiles from point clouds
homepage_url: https://github.com/3dTrees-earth/3dtrees_py3dtiles
long_description: |
  generates 3D tiles from point clouds
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/3dtrees_py3dtiles
type: unrestricted
categories:
- Geo Science
