name: package_imagej_1_48
owner: iuc
description: Contains a tool dependency definition that downloads and extracts version
  1.48 of ImageJ.
homepage_url: http://imagej.nih.gov/ij/
long_description: |
  ImageJ is a public domain Java image processing program inspired by NIH Image for the Macintosh.
  It runs, either as an online applet or as a downloadable application, on any computer with a
  Java 1.4 or later virtual machine. Downloadable distributions are available for Windows, Mac OS,
  Mac OS X and Linux.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/packages/package_imagej_1_48
type: tool_dependency_definition
categories:
  - Tool Dependency Packages
