categories:
  - RNA
description: Prediction and comparison of RNA secondary structures
long_description: |
    The ViennaRNA Package consists of a C code library and several stand-alone programs for the prediction and comparison of RNA secondary structures. 
name: vienna_rna
owner: rnateam
type: unrestricted
