name: coprarna
owner: rnateam
description: Target prediction for prokaryotic trans-acting small RNAs 
long_description: |
        CopraRNA is a tool for sRNA target prediction. It computes whole genome target predictions by combination of distinct whole genome IntaRNA predictions. As input CopraRNA requires at least 3 homologous sRNA sequences from 3 distinct organisms in FASTA format. Furthermore, each organisms' genome has to be part of the NCBI Reference Sequence (RefSeq) database (i.e. it should have exactly this NZ_* or this NC_XXXXXX format where * stands for any character and X stands for a digit between 0 and 9). Depending on sequence length (target and sRNA), amount of input organisms and genome sizes, CopraRNA can take up to 24h or longer to compute.
homepage_url: https://github.com/PatrickRWright/CopraRNA
remote_repository_url: https://github.com/PatrickRWright/CopraRNA
type: unrestricted
categories:
  - RNA
  - Sequence Analysis
