categories:
- RNA
- Sequence Analysis
description: Compute fractional identity between trusted alignment and test alignment
name: compalignp
owner: rnateam
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/rna_tools/compalignp/
type: unrestricted
