categories: 
  - Metagenomics
description: "Group abundances of UniRef50 gene families obtained with HUMAnN2 to Gene Ontology (GO) slim terms with relative abundances"
name: group_humann2_uniref_abundances_to_go
owner: bebatut
homepage_url: https://github.com/bgruening/galaxytools/tree/master/tools/group_humann2_uniref_abundances_to_GO
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/group_humann2_uniref_abundances_to_GO
