name: pubchem_rest_tool
owner: bgruening
description: This tool fetches data from pubchem via the PubChem REST API.
homepage_url: https://pubchem.ncbi.nlm.nih.gov/pug_rest/PUG_REST.html
long_description: |
  This tool fetches data from pubchem via the PubChem REST API. 
  https://pubchem.ncbi.nlm.nih.gov/pug_rest/PUG_REST.html
  https://pubchem.ncbi.nlm.nih.gov/pug_rest/PUG_REST_Tutorial.html
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/rest_tool
type: unrestricted
categories:
- Data Source



