categories:
- Sequence Analysis
- Variant Analysis
description: A tool set for short variant discovery in genetic sequence data.
long_description: |
    A tool set for short variant discovery in genetic sequence data.
    Visit http://genome.sph.umich.edu/wiki/vt for more informations
name: vt
owner: bgruening
remote_repository_url: https://github.com/atks/vt
type: unrestricted
