name: create_tool_recommendation_model
owner: bgruening
description: "Create model to recommend tools"
homepage_url: https://github.com/bgruening/galaxytools
long_description: 
    Create model to recommend tools using deep learning.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/recommendation_training/tools/tool_recommendation_model
type: unrestricted
categories:
- Machine Learning

