name: minHash
owner: joachimwolff
description: A tool to compute the nearest neighbors in a high dimensional sparse dataset.

long_description: |
  MinHash is an approximate nearest neighbors search algorithm for high dimensional sparse datasets. It computes first a candidate set with MinHash and after the 
  exact neighbors with the euclidean distance or cosine similarity.

categories:
  - Machine Learning
  
remote_repository_url: https://github.com/joachimwolff/galaxytools/tree/minHash/tools/minHash

auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for the the approximate nearest neighbors search algorithm MinHash: {{ tool_name }}"

