categories:
- Sequence Analysis
description: Find subsequences in db
long_description: |
    The GotohScan program is a search tool that finds shorter sequences
    (usually genes) in large database sequences (chromosomes, genomes, ..)
    by computing all semi-global alignments.  Thus, the query sequence is
    never truncated or split into subsequences, but always mapped to the
    database over its complete length. The alignment is computed via the
    Gotoh-alignment algorithm using affine gap costs.
name: gotohscan
owner: rnateam
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/gotohscan
type: unrestricted
