name: infernal
owner: bgruening
description: Infernal ("INFERence of RNA ALignment") is for searching DNA sequence databases for RNA structure and sequence similarities.
homepage_url: http://infernal.janelia.org/
long_description: |
  Infernal ("INFERence of RNA ALignment") is for searching DNA sequence databases for RNA structure and sequence 
  similarities. It is an implementation of a special case of profile stochastic context-free grammars called 
  covariance models (CMs). A CM is like a sequence profile, but it scores a combination of sequence consensus and 
  RNA secondary structure consensus, so in many cases, it is more capable of identifying RNA homologs that conserve 
  their secondary structure more than their primary sequence. http://infernal.janelia.org/
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/infernal
type: unrestricted
categories:
- RNA
