categories:
- Sequence Analysis
- RNA
description: Sailfish is a tool for transcript quantification from RNA-seq data
homepage_url: http://www.cs.cmu.edu/~ckingsf/software/sailfish/
long_description: |
  Sailfish is a tool for transcript quantification from RNA-seq data. It requires a set of target transcripts
  (either from a reference or de-novo assembly) to quantify. All you need to run sailfish is a fasta file containing your reference
  transcripts and a (set of) fasta/fastq file(s) containing your reads. Sailfish runs in two phases; indexing and quantification.
  The indexing step is independent of the reads, and only needs to be run once for a particular set of reference transcripts and
  choice of k (the k-mer size). The quantification step, obviously, is specific to the set of RNA-seq reads and is thus run more frequently
  Additional covariates may optionally be provided to further inform the peak-calling process. 

  https://github.com/kingsfordgroup/sailfish
name: sailfish
owner: bgruening
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/sailfish
type: unrestricted
