name: blockclust
owner: rnateam
description: BlockClust detects transcripts with similar processing patterns.
homepage_url: https://github.com/bgruening/galaxytools/tree/master/workflows/blockclust
long_description: BlockClust detects transcripts with similar processing patterns. It proposes a novel way to encode expression profiles in compact discrete structures which can then be processed using fast graph-kernel techniques. BlockClust allows both clustering and classification of small non-coding RNAs.https://github.com/bgruening/galaxytools/tree/master/workflows/blockclust
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/rna_tools/blockclust
type: unrestricted
categories:
- RNA
