name: chatgpt_openai_api
owner: bgruening
description: Using the OpenAI GPT models to generate text based on user input.
long_description: |
  This tool uses the OpenAI GPT models to generate text based on user input.
  Users can specify the model, provide context, and ask a question.
  The tool will then generate and return the corresponding text based on the input provided.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/chatgpt
homepage_url: https://github.com/bgruening/galaxytools/tree/master/tools/chatgpt
type:
categories:
  - Machine Learning
maintainers:
  - arash77
