name: chatgpt_openai_api
owner: bgruening
description: Using OpenAI-compatible LLM APIs to generate text based on user input.
long_description: |
  This tool uses OpenAI-compatible APIs (OpenAI or custom servers)
  to generate text based on user input. Users can specify the server type and model,
  provide context files, and ask a question. The tool supports advanced parameters
  like temperature, max tokens, top_p, and system messages.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/chatgpt
homepage_url: https://github.com/bgruening/galaxytools/tree/master/tools/chatgpt
type:
categories:
  - Machine Learning
maintainers:
  - arash77
