name: chatGPT
description: Using the OpenAI GPT models to generate text based on user input.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/chatgpt
homepage_url: https://github.com/bgruening/galaxytools/tree/master/tools/chatgpt
type:
categories:
  - Machine Learning
maintainers:
  - arash77
