name: methtools
owner: bgruening
description: tools for methylation analysis 
homepage_url: https://github.com/bgruening/galaxytools/tree/master/tools/methtools
long_description: |
 Tools for methylation analysis. https://github.com/bgruening/galaxytools/tree/master/tools/methtools
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/methtools
type: unrestricted
categories:
- Sequence Analysis
