name: cmsearch_deoverlap
owner: rnateam
description: removes lower scoring overlaps from cmsearch results.
homepage_url: https://github.com/EBI-Metagenomics/pipeline-v5/blob/master/tools/RNA_prediction/cmsearch-deoverlap/cmsearch-deoverlap.pl
long_description: |
  Remove overlapping hits to models in the same clan in a single tblout file.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/rna_tools/cmsearch_deoverlap
categories:
- RNA