name: pharmcat
owner: bgruening
description: Pharmacogenomics Clinical Annotation Tool
homepage_url: https://pharmcat.org/
long_description: |
  Pharmcat extracts all PGx variants, beginning 
  with variants with CPIC guideline recommendations, 
  from a genetic dataset resulting from sequencing 
  or genotyping, as represented as VCF data
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/pharmcat
type: unrestricted
categories:
- Variant Analysis
