name: nanopolish
owner: bgruening
description: Nanopolish software package for signal-level analysis of Oxford Nanopore sequencing data. 
homepage_url: https://github.com/jts/nanopolish
long_description: |
  Nanopolish can calculate an improved consensus sequence for a draft genome assembly, detect base 
  modifications, call SNPs and indels with respect to a reference genome and more.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/nanopolish
type: unrestricted
suite:
  name: "suite_nanopolish"
  description: "Nanopolish software package"
  type: repository_suite_definition

