categories:
- Computational chemistry
description: NP-Likeness calculates natural product-likeness of small molecules based on open-data of natural products
long_description: |
    Calculates Natural Product(NP)-likeness of a molecule, i.e. the similarity of the molecule to the structure space covered by known natural products. 
    NP-likeness is a useful criterion to screen compound libraries and to design new lead compounds.

homepage_url: https://sourceforge.net/projects/np-likeness/
name: natural_product_likeness
owner: bgruening
remote_repository_url: https://github.com/CS76/NP-Likeness
type: unrestricted
