name: cellpose
owner: bgruening
categories:
  - Imaging
description: Cellpose is an anatomical segmentation algorithm 
homepage_url: https://github.com/MouseLand/cellpose
long_description: |
  A generalist algorithm for cell and nucleus segmentation (v1.0) that can be optimized 
  for your own data (v2.0) and (NEW) perform image restoration (v3.0).
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/cellpose
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Tool for cell and nucleus segmentation {{ tool_name }}"

