sudo: false
language: python
python: 2.7

env:
  - CHUNK=xaa
  - CHUNK=xab
  - CHUNK=xac
  - CHUNK=xad

before_install:
  - export GALAXY_REPO=https://github.com/galaxyproject/galaxy
  - export GALAXY_RELEASE=release_16.04
  - export CONDA_PREFIX="$HOME/conda"

install:
  - pip install -q flake8 planemo lxml
  - planemo conda_init --conda_prefix "$CONDA_PREFIX"
  - export PATH="$CONDA_PREFIX/bin:$PATH"
  - conda create -y -q -c bioconda --name iuc_conda samtools=0.1.19 bcftools
  - . activate iuc_conda
  - planemo --version
  - conda --version
  - echo $TRAVIS_COMMIT_RANGE
  - planemo shed_lint --report_level warn --tools --fail_level error --recursive .
  - git diff --name-only $TRAVIS_COMMIT_RANGE | xargs -n1 dirname | ./filter_directories.py 
  # Tools that needs testing
  - sort -u tests.txt > changed_repositories.list
  - cat changed_repositories.list
  # All directories that needs to be uploaded
  - cat uploads.txt

script:
  - cd "$TRAVIS_BUILD_DIR" #&& flake8 -v --exclude=.git .
  - |
    if [ -s changed_repositories.list ]
    then
      split -n l/4 changed_repositories.list
    fi
  - echo "$CHUNK"
  - |
    if [ "${CHUNK}" ] && [ -s "${CHUNK}" ]
    then
      cat "$CHUNK"
      export PLANEMO_TEST_RUN=True
      while read -r DIR; do planemo conda_install --conda_ensure_channels r,bioconda,iuc,bgruening --conda_prefix "$CONDA_PREFIX" "$DIR"; done < "$CHUNK"
      while read -r DIR; do planemo test --conda_dependency_resolution --conda_prefix "$CONDA_PREFIX" --galaxy_branch $GALAXY_RELEASE --galaxy_source $GALAXY_REPO "$DIR" || exit 1; done < "$CHUNK"
    fi

after_success:
  # We would need to calculate the DAG from the repositories to upload them in the correct direction, but I don't think
  # this is worth for packages nowadays. Also package uploads now happens multiple times.
  - while read -r DIR; do dirname "$DIR" || exit 1; done < "$CHUNK" | sort -u > chunks.txt
  - cat chunks.txt >> uploads.txt
  - |
    if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" -a "$PLANEMO_TEST_RUN" == 'True' ]
    then
      while read -r DIR; do planemo shed_update --shed_target testtoolshed --shed_email $SHED_EMAIL --shed_password $SHED_PASSWORD --force_repository_creation "$DIR" || exit 1; done < uploads.txt
    fi
