language: python
python: 2.7

matrix:
  include:
    - python: 2.7
      env: CHUNK=xaa
    - python: 2.7
      env: CHUNK=xab
    - python: 2.7
      env: CHUNK=xac
    - python: 2.7
      env: CHUNK=xad

before_install:
  - export GALAXY_REPO=https://github.com/galaxyproject/galaxy
  - export GALAXY_RELEASE=release_16.04
  - export CONDA_PREFIX=$HOME/conda

install:
  - pip install flake8
  - pip install -q click==5.1
  - pip install -q planemo
  - planemo conda_init --conda_prefix $CONDA_PREFIX
  - export PATH=$CONDA_PREFIX/bin:$PATH
  - conda install -y -q conda=3.19.3
  - conda create -y -q -c bioconda --name iuc_conda numpy==1.9.2 samtools bcftools
  - source activate iuc_conda
  - planemo --version
  - echo $TRAVIS_COMMIT_RANGE
  - planemo shed_lint --report_level warn --tools --fail_level error --recursive .
  - git diff --name-only $TRAVIS_COMMIT_RANGE | xargs -n1 dirname | ./filter_directories.py | sort -u > changed_repositories.list
  - cat changed_repositories.list

script:
##  - cd $TRAVIS_BUILD_DIR && flake8 -v --exclude=.git .
  - |
    if [ -s changed_repositories.list ]
    then
      split -n l/4 changed_repositories.list
      export PLANEMO_TEST_RUN="True"
    fi
  - echo $CHUNK
  - |
    if [ ${CHUNK} ] && [ -s ${CHUNK} ] 
    then
      cat $CHUNK
      for DIR in `cat $CHUNK`; do planemo conda_install --conda_ensure_channels iuc,bioconda,r,bgruening --conda_prefix $CONDA_PREFIX $DIR ; done
      for DIR in `cat $CHUNK`; do planemo test --conda_dependency_resolution --conda_prefix $CONDA_PREFIX --galaxy_branch $GALAXY_RELEASE  --galaxy_source $GALAXY_REPO --skip_venv $DIR || exit 1; done
    fi
    

after_success:
  - | 
    if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" -a "$PLANEMO_TEST_RUN" == "True" ]
    then 
      for DIR in `cat changed_repositories.list`; do planemo shed_update --shed_target testtoolshed --shed_email $SHED_EMAIL --shed_password $SHED_PASSWORD --force_repository_creation $DIR || exit 1; done
    fi
