language: python
python: 2.7

before_install:
  - export GALAXY_REPO=https://github.com/galaxyproject/galaxy
  - export GALAXY_RELEASE=release_16.01
  - export CONDA_PREFIX=$HOME/conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $CONDA_PREFIX
  - export PATH=$CONDA_PREFIX/bin:$PATH
  - conda install --yes conda=3.19.3

install:
  - conda create -y -q -c bioconda --name iuc_conda numpy==1.9.2 samtools bcftools planemo
  - source activate iuc_conda
  - planemo --version
  - echo $TRAVIS_COMMIT_RANGE
  - planemo shed_lint --report_level warn --tools --fail_level error --recursive .
  - git diff --name-only $TRAVIS_COMMIT_RANGE | xargs -n1 dirname | ./filter_directories.py | sort -u > changed_repositories.list
  - cat changed_repositories.list

script:
  - |
    if [ -s changed_repositories.list ]
    then
      for DIR in `cat changed_repositories.list`; do planemo conda_install --conda_ensure_channels bgruening,bioconda,r --conda_prefix $CONDA_PREFIX $DIR ; done
      for DIR in `cat changed_repositories.list`; do planemo test --conda_dependency_resolution --conda_prefix $CONDA_PREFIX --galaxy_branch $GALAXY_RELEASE  --galaxy_source $GALAXY_REPO $DIR || exit 1; done
      export PLANEMO_TEST_RUN="True"
    fi
    

after_success:
  - | 
    if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" -a "$PLANEMO_TEST_RUN" == "True" ]
    then 
      for DIR in `cat changed_repositories.list`; do planemo shed_update --shed_target testtoolshed --shed_email $SHED_EMAIL --shed_password $SHED_PASSWORD --force_repository_creation $DIR || exit 1; done
    fi
