categories:
- Next Gen Mappers
description: segemehl - short read mapping with gaps
long_description: |
  segemehl is a software to map short sequencer reads to reference genomes.
  Unlike other methods, segemehl is able to detect not only mismatches but also
  insertions and deletions. Furthermore, segemehl is not limited to a specific
  read length and is able to mapprimer- or polyadenylation contaminated reads
  correctly. segemehl implements a matching strategy based on enhanced suffix
  arrays (ESA). Segemehl now supports the SAM format, reads gziped queries to
  save both disk and memory space and allows bisulfite sequencing mapping and
  split read mapping.

  http://www.bioinf.uni-leipzig.de/Software/segemehl/
name: segemehl
owner: rnateam
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/segemehl
homepage_url: http://www.bioinf.uni-leipzig.de/Software/segemehl/
type: unrestricted
