name: intarna
owner: rnateam
description: Efficient RNA-RNA interaction prediction incorporating accessibility and seeding of interaction sites.
homepage_url: http://www.bioinf.uni-freiburg.de/Software
long_description: |
  During the last few years, several new small regulatory RNAs (sRNAs) have been discovered in bacteria.
  Most of them act as post-transcriptional regulators by base pairing to a target mRNA, causing translational
  repression or activation, or mRNA degradation. Numerous sRNAs have already been identified, but the number
  of experimentally verified targets is considerably lower. Consequently, computational target
  prediction is in great demand. Many existing target prediction programs neglect the accessibility of target
  sites and the existence of a seed, while other approaches are either specialized to certain types of RNAs or too
  slow for genome-wide searches.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/rna_tools/intarna
type: unrestricted
categories:
- RNA
