categories:
- RNA
- Data Source
description: data source for RNA interactions in post-transcriptional regulation
long_description: |
  The expression of almost all genes in animals is subject to post-transcriptional regulation by RNA binding proteins (RBPs) and microRNAs (miRNAs).
  The interactions between both RBPs and miRNAs with mRNA can be mapped on a whole-transcriptome level using experimental and computational techniques.
  doRiNA is a RESTful webservice that collects data from such experiments.
name: dorina
owner: rnateam
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/rna_tools/dorina/
type: unrestricted
