name: 3dtrees_raycloudtools
owner: bgruening
description: forest instance segmentation
homepage_url: https://github.com/3dTrees-earth/3dtrees_rct
long_description: |
  Performs forest instance segmentation on point clouds using RayCloudTools rayextract trees.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/3dtrees_raycloudtools
type: unrestricted
categories:
- "Geo Science"
