categories:
- Computational chemistry
description: OSRA - Optical Structure Recognition Application
long_description: |
    OSRA is a utility designed to convert graphical representations of chemical structures,
    as they appear in journal articles, patent documents, textbooks, trade magazines etc., into SMILES.
name: osra
owner: bgruening
homepage_url: https://cactus.nci.nih.gov/osra/
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/chemicaltoolbox/osra
type: unrestricted
