name: flexynesis
owner: bgruening
description: This is a deep-learning based multi-omics bulk sequencing data integration suite with a focus on (pre-)clinical endpoint prediction.
homepage_url: https://github.com/BIMSBbioinfo/flexynesis/tree/main
long_description: The package includes multiple types of deep learning architectures such as simple fully connected networks, supervised variational autoencoders, graph convolutional networks, multi-triplet networks different options of data layer fusion, and automates feature selection and hyperparameter optimisation.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/flexynesis
categories: 
- Machine Learning
- Statistics
- Systems Biology
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for {{ tool_name }}."
suite:
  name: "suite_flexynesis"
  description: "A suite of Galaxy tools designed to work with the flexynesis-tools collection."
  type: repository_suite_definition
