categories: [RNA]
description: Redundant GraphClust clusters are merged and instances that belong
  to multiple clusters are assigned unambiguously.
long_description: Post-processing. Redundant clusters are merged and instances that
  belong to multiple clusters are assigned unambiguously. For every pair of clusters,
  the relative overlap (i.e. the fraction of instances that occur in both clusters)
  is computed and clusters are merged if the overlap exceeds 50%. instances that occur
  in both clusters) is computed and clusters are merged if the overlap exceeds 50%.
name: graphclust_postprocessing_no_align
owner: rnateam
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/GraphClust/CollectResultsNoAlign
