name: imagemagick
owner: bgruening
description: Contains tools based on ImageMagick
homepage_url: https://imagemagick.org/
long_description: |
    ImageMagick is a free, open-source software suite, used for editing and manipulating digital images. 
    It can be used to create, edit, compose, or convert bitmap images, and supports a wide range of file formats, including JPEG, PNG, GIF, TIFF, and Ultra HDR.

remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/image_processing/imagemagick
type: unrestricted
categories:
  - Imaging
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for the ImageMagick suite: {{ tool_name }}"
suite:
  name: "suite_imagemagick"
  description: Contains tools based on ImageMagick
  long_description: |
    ImageMagick is a free, open-source software suite, used for editing and manipulating digital images. 
    It can be used to create, edit, compose, or convert bitmap images, and supports a wide range of file formats, including JPEG, PNG, GIF, TIFF, and Ultra HDR.
