name: trna_prediction
owner: bgruening
description: Aragorn predicts tRNA and tmRNA in nucleotide sequences.
homepage_url: http://mbioserv2.mbioekol.lu.se/ARAGORN/
long_description: Aragorn predicts tRNA and tmRNA in nucleotide sequences. http://mbioserv2.mbioekol.lu.se/ARAGORN/
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/rna_tools/trna_prediction
type: unrestricted
categories:
- RNA
