name: trna_prediction
owner: bgruening
description: tRNA and tmRNA prediction from nucleotide sequences.
homepage_url: https://github.com/UCSC-LoweLab/tRNAscan-SE
long_description: tRNA prediction using tRNAscan-SE (https://github.com/UCSC-LoweLab/tRNAscan-SE) and Aragorn (https://www.trna.se/)
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/rna_tools/trna_prediction
type: unrestricted
categories:
- RNA
- Sequence Analysis
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for the tool: {{ tool_name }}"
