categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads version 2.2.12 of pkiss of the RNAShapesStudio.
long_description: |
  pKiss is a tool for secondary structure prediction including kissing hairpin motifs.
  http://bibiserv.techfak.uni-bielefeld.de/rnashapesstudio
name: package_pkiss_2_2_12
owner: rnateam
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/packages/package_pkiss_2_2_12
type: tool_dependency_definition
