name: mitohifi
owner: bgruening
description:  Circularises, cuts and annotates the mitogenome
homepage_url: https://github.com/marcelauliano/MitoHiFi 
long_description: |
  Circularises, cuts and annotates the mitogenome from contigs assembled with PacBio HiFi reads and software such as HiCanu or Hifiasm.
remote_repository_url: https://https://github.com/bgruening/galaxytools/tree/master/tools/mitohifi
type: unrestricted
categories:
- Genome annotation
