name: mitohifi
owner: bgruening
description: Assembly mitogenomes from Pacbio HiFi read.
homepage_url: https://github.com/marcelauliano/MitoHiFi/tree/mitohifi_v2
long_description: |
    MitoHiFi is a python pipeline developed to finalise the assembly and annotation of mitogenomes.
    It also detect different variants of the mitogenome present in the sample, and choose a final 
    consensus sequence.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/bismark
type: unrestricted
categories:
- Assembly