name: High-Throughput Sequencing Metadata
owner: bgruening
description: This tool produces a tsv file containing the High-throughput sequencing metadata template (version 2.1)
homepage_url: https://github.com/bgruening/galaxytools
type: unrestricted
categories:
- Data Managers
