name: odose
owner: bgruening
description: ODoSE: a webserver for genome-wide calculation of adaptive divergence in prokaryotes.
homepage_url: https://github.com/ODoSE/odose.nl
type: unrestricted
categories:
- Tool Dependency Packages
