categories:
- Sequence Analysis
description: Detect protein translational efficiency difference
homepage_url: https://github.com/ratschlab/RiboDiff
long_description: |
  RiboDiff_ is a tool for detecting protein translational efficiency difference based on data from high-throughput deep sequencing assays such as RNA-Seq and Ribosome footprinting.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/ribodiff
name: ribodiff
owner: rnateam
type: unrestricted
