name: minced
owner: bgruening
description: MinCED - Mining CRISPRs in Environmental Datasets
homepage_url: http://bioweb2.pasteur.fr/docs/modules/minced/0.1.5/_README
long_description: |
  MinCED is a program to find Clustered Regularly Interspaced Short Palindromic
  Repeats (CRISPRs) in full genomes or environmental datasets such as metagenomes,
  in which sequence size can be anywhere from 100 to 800 bp. 
  http://bioweb2.pasteur.fr/docs/modules/minced/0.1.5/_README
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/minced
type: unrestricted
categories:
- Sequence Analysis
