categories:
- Data Managers
- Metagenomics
description: Contains a data manager that populates the motus DB
  tool data table.
homepage_url: https://github.com/bgruening/galaxytools/
long_description: |
  This data managers fetches data for motus
name: data_manager_motus
owner: bgruening
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/data_managers/
type: unrestricted
