categories:
    - Convert Formats
    - Statistics
    - Fasta Manipulation
description: GTF/GFF analysis toolkit
homepage_url: https://github.com/NBISweden/AGAT
long_description: |
    AGAT has the power to check, fix, pad missing information (features/attributes) of any 
    kind of GTF and GFF to create complete, sorted and standardised gff3 format. Over the 
    years it has been enriched by many many tools to perform just about any tasks that is 
    possible related to GTF/GFF format files (sanitizing, conversions, merging, modifying, 
    filtering, FASTA sequence extraction, adding information, etc). Comparing to other 
    methods AGAT is robust to even the most despicable GTF/GFF files.
name: AGAT
owner: bgruening
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/agat
type: unrestricted
