name: quast
owner: bgruening
description: Quality assessment tool for genome assemblies
homepage_url: http://bioinf.spbau.ru/quast
long_description: |
  QUAST evaluates genome assemblies.
  It can works both with and without a given reference genome.
  The tool accepts multiple assemblies, thus is suitable for comparison.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/quast
type: unrestricted
categories:
- Assembly
- Metagenomics
