categories:
- Sequence Analysis
- RNA
description: "Dot-Bracket to Connect Table (CT)"
long_description: |
  Converts the first sequence in a Dot-Bracket file into a CT file

  Part of the RNAStructure package:
  http://rna.urmc.rochester.edu/Overview/Components.html
name: dot2ct
owner: rnateam
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/rna_tools/dot2ct
type: unrestricted