categories:
- Sequence Analysis
- RNA
description: "Dot-Bracket to Connect Table (CT)"
long_description: |
  Converts the first sequence in a Dot-Bracket file into a CT file

  Party of the RNAStructure package.
name: dot2ct
owner: rnateam
remote_repository_url: https://github.com/yhoogstrate/galaxytools/tree/master/tools/rna_tools/dot2ct
type: unrestricted