categories:
- - Sequence Analysis
description: Search a FASTA sequence against a library of Pfam HMM.
homepage_url: http://ftp.ebi.ac.uk/pub/databases/Pfam/Tools/
long_description: |
    Search one or more sequences for matching Pfam domains. Depending on the user options, 
    the script can also process the results such that overlaps between families belonging 
    to the same clan are resolved and can predict active sites.
name: pfam_scan
owner: bgruening
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/pfamscan
type: unrestricted
