name: imagej2_smooth
owner: iuc
description: |
  Contains a tool that wraps the ImageJ2 Smooth command.
homepage_url: http://rsb.info.nih.gov/ij/docs/menus/process.html
long_description: |
  Contains a tool that blurs the image by replacing each pixel with the average
  of its 3x3 neighborhood.
remote_repository_url:
type: unrestricted
categories:
- Imaging
