categories:
- Sequence Analysis
- Next Gen Mappers
description: Generates a graphical HTML report page from report outputs of Bismark
long_description: |
    This tool uses a Bismark alignment report to generate a graphical HTML report page.
    Optionally, further reports of the Bismark suite such as deduplication, methylation extractor splitting or M-bias reports can be specified as well.
    http://www.bioinformatics.babraham.ac.uk/projects/bismark/
name: bismark
owner: bgruening
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/bismark/bismark_pretty_report
type: unrestricted