name: webatlas
owner: iuc
description: The Galaxy WebAtlas tools to process spatial and single-cell experiment data for visualisation in a web browser using Vitessce.
homepage_url: https://github.com/haniffalab/webatlas-pipeline
long_description: The Galaxy WebAtlas tools provide a framework for processing spatial and single-cell experiment data, enabling visualisation with Vitessce.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/webatlas
categories:
- Spatial Omics
- Single Cell
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for {{ tool_name }}."
suite:
  name: "suite_webatlas"
  description: "A suite of Galaxy tools to process single-cell and spatial experiment data for visualisation using Vitessce."
  type: repository_suite_definition