categories: 
  - Metagenomics
description: Format MetaPhlAn2 output to extract abundance at different taxonomic levels
name: format_metaphlan2_output
owner: bebatut
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/format_metaphlan2_output/
