categories:
- Text Manipulation
description: Split a multi-sequence fasta file into files containing single sequences
long-description: |
    Very basic utility, that grabs lines two by two, and writes them to a file.
name: split_fasta
owner: rnateam
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/split_fasta
type: unrestricted
