name: imagej2_noise
owner: iuc
description: Contains a tool that adds specified noise to or removes specified noise from and image.
homepage_url: http://fiji.sc/Fiji
long_description: |
  Adds noise to or removes noise from images using the following options:
  -Add Random Noise: Adds random noise to the image or selection.
  -Add Specified Noise: Adds Gaussian noise with a mean of zero and a chosen standard deviation.
  -Salt and Pepper: Adds Gaussian noise with a mean of zero and a chosen standard deviation.
  -Despeckle: Replaces each pixel with the median value in its 3 × 3 neighborhood.
  -Remove Outliers: Replaces a pixel by the median of the pixels in the surrounding if it deviates from the median by more than a certain value (the threshold).
  -Remove NaNs: replaces NaN (Not-a-Number) pixels in 32-bit (float) images by the median of the neighbors inside the circular kernel area defined by Radius.
  -RandomJ: Introduce randomness into images for testing the robustness of image processing algorithms.
remote_repository_url:
type: unrestricted
categories:
- Imaging
