categories:
- Sequence Analysis
- RNA
description: PEAKachu is a peak-caller for CLIP- and RIP-Seq data
long_description: |
  PEAKachu is a peak-caller for CLIP- and RIP-Seq data. It takes input in BAM format and identifies regions of statistically significant read enrichment.
  PEAKachu uses signal and control libraries (ideally more than three each) to detect binding sites. It implements two peak calling approaches
name: peakachu
owner: rnateam
remote_repository_url: https://github.com/tbischler/PEAKachu
type: unrestricted
