name: epicseg
owner: wkopp
description: EpiCSeg is a tool for conducting chromatin segmentation.
homepage_url: https://github.com/lamortenera/epicseg
long_description: |
 EpiCSeg is a tool for performing chromatin segmentation based on
 a hidden Markov model approach. 
 A detailed description of the method is available under
 http://www.genomebiology.com/2015/16/1/151 .
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/epicseg
type: unrestricted
categories:
- Epigenetics
- Chromatin segmentation
