name: rnabob
owner: rnateam
description: Fast pattern searching for RNA structural motifs
homepage_url: http://eddylab.org/software.html
long_description: |
  RNABOB is an implementation of D. Gautheret's RNAMOT, but with a different underlying algorithm using a
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/rna_tools/rnabob
type: unrestricted
categories:
  - RNA
