name: 3dtrees_overviews
owner: bgruening
description: generates 3D overview images
homepage_url: https://github.com/3dTrees-earth/tool_overviews
long_description: |
  generates 3D overview images of point clouds
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/3dtrees_overviews
type: unrestricted
categories:
- "Geo Science"
