name: carveme
owner: bgruening
long_description: CarveMe is a tool to reconstruct genome scale metabolic models
homepage_url: https://github.com/cdanielmachado/carveme
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/carveme
categories:
- Systems Biology