name: Preprocessing
owner: rnateam
description: "Preprocessing input for GraphClust"
long_description: |
The tool takes as an input file of sequences in Fasta format and creates the final input for GraphCLust based on given parameters.
remote_repository_url: https://github.com/eteriSokhoyan/galaxytools/tree/branchForIterations/tools/GraphClust/Preprocessing
categories:
  - RNA

