name: deseq2
owner: bgruening
description: Estimate variance-mean dependence in count data from high-throughput sequencing assays and test for differential expression. 
homepage_url: http://bioconductor.org/packages/release/bioc/html/DESeq2.html
long_description: Estimate variance-mean dependence in count data from high-throughput sequencing assays and test for differential expression based on a model using the negative binomial distribution http://bioconductor.org/packages/release/bioc/html/DESeq2.html
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/deseq2
type: unrestricted
categories:
- Sequence Analysis
- RNA
- Statistics
