categories:
- RNA
description: Maximum expected accuracy prediction
long_description: |
    Predict maximum expected accuracy secondary structures
    of RNAs and compare RNA secondary structures.
name: mea
owner: rnateam
type: unrestricted
