categories:
- RNA
description: Maximum expected accuracy prediction
long_description: |
    Predict maximum expected accuracy secondary structures
    of RNAs and compare RNA secondary structures.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/rna_tools/mea
homepage_url: http://www.bioinf.uni-leipzig.de/Software/mea
name: mea
owner: rnateam
type: unrestricted
