name: hclust2
owner: yuanbit
remote_repository_url: "https://github.com/yuanbit/galaxytools/tree/hclust2/tools/hclust2"
homepage_url: "https://github.com/yuanbit/galaxytools/tree/hclust2/tools/hclust2"
categories:
  - Data Visualization
description: Plots heatmaps
long_description: |
 hclust2 is a handy tool for plotting heat-maps with several 
 useful options to produce high quality figures that can be 
 used in publication.
include:
  - hclust2.xml
  - hclust2_macros.xml
  - test-data