name: hclust2
owner: galaxytools
description: Plots heatmaps
remote_repository_url: "https://github.com/yuanbit/galaxytools/tree/hclust2/tools/hclust2"
homepage_url: "https://bitbucket.org/nsegata/hclust2/"
categories:
  - Data Visualization
long_description: |
 hclust2 is a handy tool for plotting heat-maps with several 
 useful options to produce high quality figures that can be 
 used in publication.
include:
  - hclust2.xml
  - test-data