name: numeric_clustering
owner: bgruening
description: Clustering tool for numberic values
homepage_url: http://scikit-learn.org/stable/index.html
long_description: |
    This clustering tool offers different clustering algorithms which are provided by
    scikit-learn to find similarities among samples and cluster the samples based on these similarities.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/numeric_clustering
type: unrestricted
categories:
- Statistics
