name: antismash
owner: bgruening
description: antiSMASH allows the rapid genome-wide identification, annotation and analysis of secondary metabolite biosynthesis gene clusters in bacterial and fungal genomes.
homepage_url: http://www.antismash.secondarymetabolites.org/
long_description: |
  antiSMASH allows the rapid genome-wide identification, annotation and analysis of secondary metabolite biosynthesis gene clusters in bacterial and fungal genomes.
  It integrates and cross-links with a large number of in silico secondary metabolite analysis tools that have been published earlier. http://www.antismash.secondarymetabolites.org/
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/antismash
type: unrestricted
categories:
- Sequence Analysis
