categories:
- Computational chemistry
description: SyGMa is a tool for the systematic generation of potential metabolites.
long_description: |
  SyGMa is a python library for the systematic generation of potential metabolites.
  Home page: https://sygma.readthedocs.io/
  License: GPL
homepage_url: https://sygma.readthedocs.io/
name: sygma
owner: bgruening
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/chemicaltoolbox/sygma
type: unrestricted
