name: imagej2_bunwarpj_compare_raw
owner: iuc
description: |
  Contains a tool that wraps the bUnwarpJ ImageJ2 plugin, restricting use to the
  "-compare_raw" option when running bUnwarpJ from the command line.
homepage_url: http://biocomp.cnb.csic.es/~iarganda/bUnwarpJ/
long_description: |
  Calculates the warping index of two raw transformations (same direction). The transformation
  files must be in "raw" format, which is the same format as the files created with the
  Convert elastic transformation to raw tool.
remote_repository_url:
type: unrestricted
categories:
- Imaging
