name: rnasnp
owner: rnateam
description: "RNAsnp Efficient detection of local RNA secondary structure changes induced by SNPs"
homepage_url: http://rth.dk/resources/rnasnp/
long_description: |
      Efficient detection of local RNA secondary structure changes induced by SNPs. RNAsnp requires an RNA sequence and optionally a list of SNPs to be analyzed. The effect of SNPs on local RNA secondary structure can be detected in three possible modes: Mode 1: The first mode is designed to compute the effect of SNPs by using global folding. This option should be used only for short input sequences, since the base pair probabilities are calculated using RNAfold. Mode 2: The second mode is designed to compute the effect of SNPs on large sequences. Here the local base pair probabilities are calculated using RNAplfold (with the parameters -W 200 and -L 120). Mode 3: The third mode is the combination of the above two. It is intended to determine the positions of putative structure-disruptive SNPs using either transcript or genome sequence.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/rnasnp
categories:
- RNA
