name: samblaster
owner: bgruening
description: for marking duplicates in read-id grouped paired-end SAM files
homepage_url: http://bioinf.spbau.ru/quast
long_description: |
    Tool to mark duplicates and optionally output split reads and/or discordant
    pairs. Input sam file must contain paired end data, contain sequence header
    and be sorted by read ids.
    Output will be all alignments in the same order as input, with duplicates 
    marked with FLAG 0x400.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/samblaster
type: unrestricted
categories:
- SAM
