name: crispr_recognition_tool
owner: bgruening
description: CRISPR Recognition Tool
long_description: |
  CRISPR Recognition Tool is a tool for automatic detection of clustered
  regularly interspaced palindromic repeats (CRISPR). It rapidly and accurately
  identifies CRISPRs in large DNA strings, such as genomes and metagenomes. 

  http://www.room220.com/crt/
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/crt
type: unrestricted
categories:
- Sequence Analysis
