name: illumina_methylation_analyser
owner: bgruening
description: Methylation analyzer for Illumina 450k DNA emthylation microarrays
homepage_url: https://github.com/bgruening/galaxytools/tree/master/tools/illumina_methylation_analyser
long_description: Methylation analyzer for Illumina 450k DNA emthylation microarrays
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/illumina_methylation_analyser
type: unrestricted
categories:
- Sequence Analysis
