name: methylation_analyser
owner: bgruening
description: antiSMASH allows the rapid genome-wide identification, annotation and analysis of secondary metabolite biosynthesis gene clusters in bacterial and fungal genomes.
homepage_url: https://github.com/bgruening/galaxytools/tree/master/tools/illumina_methylation_analyser
long_description: for Illumina 450k DNA emthylation microarrays https://github.com/bgruening/galaxytools/tree/master/tools/illumina_methylation_analyser
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/illumina_methylation_analyser
type: unrestricted
categories:
- Sequence Analysis
