name: remurna
owner: rnateam
description: "remuRNA - Measurement of Single Nucleotide Polymorphism induced Changes of RNA Conformation"
homepage_url: https://www.ncbi.nlm.nih.gov/CBBresearch/Przytycka/index.cgi#remurna
long_description: |
 Single-nucleotide polymorphisms (SNPs) are often linked to critical phenotypes such as diseases or responses to vaccines, medications and environmental factors. However, the specific molecular mechanisms by which a causal SNP acts is usually not obvious. Changes in RNA secondary structure emerge as a possible explanation necessitating the development of methods to measure the impact of single-nucleotide variation on RNA structure. To answer this need, remuRNA commutes the relative entropy between the Boltzmann ensembles of the native and a mutant structure.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/rna_tools/remurna
categories:
  - RNA
