name: wtaHash
owner: bgruening
description: A tool to compute the nearest neighbors in a high dimensional sparse dataset.

long_description: |
  WtaHash is an approximate nearest neighbors search algorithm for high dimensional sparse datasets. It computes first a candidate set with WtaHash and after the 
  exact neighbors with the euclidean distance or cosine similarity.
  
categories:

remote_repository_url: https://github.com/joachimwolff/galaxytools/tree/wtaHash/tools/wtaHash