name: imagej2_adjust_threshold_binary
owner: iuc
description: |
  Contains a tool that wraps the ImageJ2 Threshold command with options.
homepage_url: http://rsbweb.nih.gov/ij/docs/guide/146-28.html
long_description: |
  Sets lower and upper threshold values, segmenting grayscale images into
  features of interest and background.
remote_repository_url:
type: unrestricted
categories:
- Imaging
