name: 3dtrees_forestmamba
owner: bgruening
description: Forest instance segmentation with ForestMamba.
homepage_url: https://github.com/3dTrees-earth/3Dtrees_ForestMamba
long_description: |
  Performs forest instance and semantic segmentation on LAZ/LAS point clouds using the
  ForestMamba model.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/3dtrees_forestmamba
type: unrestricted
categories:
- "Geo Science"
