categories: 
  - Metagenomics 
description: Compare outputs of HUMAnN2 for several samples and extract similar and specific information
name: compare_humann2_output
owner: bebatut
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/compare_humann2_output
