name: imagej2_bunwarpj_adapt_transform
owner: iuc
description: |
  Contains a tool that wraps the bUnwarpJ ImageJ2 plugin, restricting use to the
  "-adapt_transform" option when running bUnwarpJ from the command line.
homepage_url: http://biocomp.cnb.csic.es/~iarganda/bUnwarpJ/
long_description: |
  Adapts an elastic transformation to a new image size by transforming the
  coefficients of a specified elastic transformation according to a real image
  factor.
remote_repository_url:
type: unrestricted
categories:
- Imaging
