name: nucleosome_prediction
owner: bgruening
description: Prediction of Nucleosomes Positions on the Genome
homepage_url: https://genie.weizmann.ac.il/software/nucleo_exe.html
long_description: |
  This tool allows you to submit a genomic sequence and to recieve a prediction of the nucleosomes positions on it, based on the      nucleosome-DNA interaction model 
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/nucleosome_prediction
type: unrestricted
categories:
- Sequence Analysis
