name: trim_galore
owner: bgruening
description: Trim Galore adaptive quality and adapter trimmer 
homepage_url: http://www.bioinformatics.babraham.ac.uk/projects/trim_galore/
long_description: |
  Trim Galore! is a wrapper script that makes use of the publically available adapter trimming tool Cutadapt and FastQC for optional quality control once the trimming process has completed.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/trim_galore
type: unrestricted
categories:
- Sequence Analysis
- Fastq Manipulation
