name: circexplorer
owner: bgruening
description: A combined strategy to identify circular RNAs (circRNAs and ciRNAs)
homepage_url: https://github.com/YangLab/CIRCexplorer
long_description: A combined strategy to identify circular RNAs (circRNAs and ciRNAs) (Zhang et al., Complementary Sequence-Mediated Exon Circularization, Cell (2014), 159:134-147)
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/circexplorer
type: unrestricted
categories:
- Sequence Analysis
- RNA
