categories:
- Computational chemistry
description: Strip-it is a program that extracts predefined scaffolds from organic small molecules
long_description: |
    Strip-it is a program that extracts predefined scaffolds from organic small molecules.

name: strip_it
homepage_url: http://silicos-it.be.s3-website-eu-west-1.amazonaws.com/software/strip-it/1.0.2/strip-it.html
owner: bgruening
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/chemicaltoolbox/silicos-it/strip-it
type: unrestricted
