categories:
- Computational chemistry
description: Strip-it is a program that extracts predefined scaffolds from organic small molecules
long_description: |
    Strip-it is a program that extracts predefined scaffolds from organic small molecules.

    Home page: http://silicos-it.be.s3-website-eu-west-1.amazonaws.com/software/strip-it/1.0.2/strip-it.html
    License: GPL3+

name: strip_it
owner: bgruening
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/chemicaltoolbox/silicos-it/strip-it
type: unrestricted
