name: markitdown
owner: bgruening
type: unrestricted
description: Convert documents to Markdown using markitdown
long_description: |
  Convert documents to Markdown using markitdown
homepage_url: https://github.com/microsoft/markitdown
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/markitdown
categories:
- Convert Formats
