name: imagej2_bunwarpj_raw_transform
owner: iuc
description: |
  Contains a tool that wraps the bUnwarpJ ImageJ2 plugin, restricting use to the
  "-raw_transform" option when running bUnwarpJ from the command line.
homepage_url: http://biocomp.cnb.csic.es/~iarganda/bUnwarpJ/
long_description: |
  Applies a raw transformation to an image, producing another image which is deformed according
  to the transformation.  The transformation file must be in the same format as the files created
  with the Convert elastic transformation to raw with bUnwarpJ tool.
remote_repository_url:
type: unrestricted
categories:
- Imaging
