name: nextdenovo
owner: bgruening
description: String graph-based de novo assembler for long reads
homepage_url: https://github.com/Nextomics/NextDenovo
long_description: |
    NextDenovo is a string graph-based de novo assembler for long reads (CLR, HiFi and ONT). It uses
    a "correct-then-assemble" strategy similar to canu (no correction step for PacBio HiFi reads), but
    requires significantly less computing resources and storages. It also detects different variants
    of the mitogenome present in the sample, and chooses a final consensus sequence.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/nextdenovo
type: unrestricted
categories:
- Assembly