name: labels
owner: bgruening
description: remaps and annotates alignments
homepage_url: https://github.com/bgruening/galaxytools/tree/master/tools/labels
long_description: |
  remapper and annotator of alignments
  https://github.com/bgruening/galaxytools/tree/master/tools/labels
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/labels
type: unrestricted
categories:
- Sequence Analysis
