name: vrhyme
owner: bgruening
description: Tool for dereplication and binning virus genomes from metagenomes.
homepage_url: https://github.com/AnantharamanLab/vRhyme
long_description:
    vRhyme is a tool for binning viral genomes from metagenomes. It groups viral contigs into metagenome-assembled genomes (vMAGs) using sequence features, read coverage patterns, and machine learning. It also includes an optional dereplication function to remove redundant sequences.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/vrhyme
categories:
  - Metagenomics
