name: platypus
owner: bgruening
description: efficient and accurate variant-detection in high-throughput sequencing data
homepage_url: http://www.well.ox.ac.uk/platypus
long_description: |
  Platypus is a tool designed for efficient and accurate variant-detection in high-throughput sequencing 
  data. By using local realignment of reads and local assembly it achieves both high sensitivity and high 
  specificity. Platypus can detect SNPs, MNPs, short indels, replacements and (using the assembly option) 
  deletions up to several kb.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/platypus
type: unrestricted
categories:
- Sequence Analysis
