categories:
- Computational chemistry
description: Systematic conformation generator
long_description: |
    Confab is an open source conformation generator whose goal is the systematic coverage of conformational space.
    Home page: https://github.com/openbabel/openbabel
    License: GPL Version 2
homepage_url: https://github.com/openbabel/openbabel
name: confab
owner: bgruening
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/chemicaltoolbox/confab
type: unrestricted
