categories:
- Computational chemistry
description: Systematic conformation generator
long_description: |
    Confab is an open source conformation generator whose goal is the systematic coverage of conformational space.
name: confab
owner: bgruening
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/chemicaltoolbox/confab
type: unrestricted
