categories:
- Computational chemistry
description: RDKit is a collection of cheminformatics and machine-learning software.
long_description: |
  RDKit is a collection of cheminformatics and machine-learning software.
  
  Home page: https://github.com/rdkit/rdkit
  License: BSD

auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "{{ tool_name }} tool from RDKit"
suite:
  name: suite_rdkit
  description: RDKit is a collection of cheminformatics and machine-learning software.
name: rdkit
owner: bgruening
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/chemicaltoolbox/rdkit
type: unrestricted
