categories: [RNA]
description: Convert RNA structure to GSPAN graphs
long_description:For each pair of sequence and structure provided in the input file
and convert them into GSPAN format graphs.

name: graphclust_structure_to_gspan
owner: rnateam
remote_repository_url: https://github.com/mmiladi/galaxytools/blob/graphclust-gspan/tools/GraphClust/Structure_GSPAN
