name: rnaz
owner: bgruening
description: RNAz is a program for predicting structurally conserved and thermodynamically stable RNA secondary structures in multiple sequence alignments.
homepage_url: https://www.tbi.univie.ac.at/~wash/RNAz/
long_description: |
  RNAz is a program for predicting structurally conserved and thermodynamically stable RNA secondary structures in multiple sequence alignments.
  It can be used in genome wide screens to detect functional RNA structures, as found in noncoding RNAs and cis-acting regulatory elements of mRNAs
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/rna_team/rnaz
categories:
  - RNA
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for RNAz application: {{ tool_name }}."
suite:
  name: "suite_rnaz"
  description: "A suite of Galaxy tools for the RNAz package."
  long_description: |
    RNAz is a program for predicting structurally conserved and thermodynamically stable RNA secondary structures in multiple sequence alignments.
    It can be used in genome wide screens to detect functional RNA structures, as found in noncoding RNAs and cis-acting regulatory elements of mRNAs
