name: rnaz
owner: bgruening
description: RNAz is a program for predicting structurally conserved and thermodynamically stable RNA secondary structures in multiple sequence alignments.
homepage_url: https://www.tbi.univie.ac.at/~wash/RNAz/
long_description: RNAz is a program for predicting structurally conserved and thermodynamically stable RNA secondary structures in multiple sequence alignments. It can be used in genome wide screens to detect functional RNA structures, as found in noncoding RNAs and cis-acting regulatory elements of mRNAs https://www.tbi.univie.ac.at/~wash/RNAz/
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/rnaz
type: unrestricted
categories:
- RNA
