categories:
- RNA
description: RNAz is a program for predicting structurally conserved and thermodynamically stable RNA secondary structures in multiple sequence alignments.
long_description: |
RNAz is a program for predicting structurally conserved and thermodynamically stable RNA secondary structures in multiple sequence alignments.
It can be used in genome wide screens to detect functional RNA structures, as found in noncoding RNAs and cis-acting regulatory elements of mRNAs
homepage_url: https://www.tbi.univie.ac.at/~wash/RNAz/
name: rnaz
owner: bgruening
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/rnaz
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for RNAz application {{ tool_name }}."
suite:
  name: "suite_rnaz_2_1"
  description: "A suite of Galaxy tools for version 2_1 of the RNAz package."
type: repository_suite_definition
