name: cmv
owner: rnateam

remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/rna_tools/cmv
homepage_url: https://github.com/eggzilla/cmv
type: unrestricted
categories:
  - RNA

description: "cmv is a collection of tools for the visualisation of Hidden Markov Models and RNA-family models."
long_description: |
    cmv is a collection of tools for the visualisation of Hidden Markov Models (HMMV)
    and RNA-family models (CMV). Moreover it can visualise comparisons of these models (HMMCV,CMCV),
    and annotate linked regions in the structural alignments they were constructed from and via,
    3rd party tools, in their consensus secondary structure.


auto_tool_repositories:
    name_template: "{{ tool_id }}"
    description_template: "Wrapper for application {{ tool_name }} of the cmv suite"
    type: unrestricted

suite:
    name: "suite_cmv"
    description: "cmv is a collection of tools for the visualisation of Hidden Markov Models and RNA-family models"
    long_description: |
            cmv is a collection of tools for the visualisation of Hidden Markov Models (HMMV)
            and RNA-family models (CMV). Moreover it can visualise comparisons of these models (HMMCV,CMCV),
            and annotate linked regions in the structural alignments they were constructed from and via,
            3rd party tools, in their consensus secondary structure.
