owner: bgruening
name: column_arrange_by_header
categories:
- Text Manipulation
description: Column arrange by header name
long_description: |
  With this tool you can specify (by naming the header) which columns need to be leftmost.
  The columns which are not specified will be ordered as before, right of the columns which were specified.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/text_processing/column_arrange_by_header
type: unrestricted
