name: protease_prediction
owner: bgruening
description: This tool can learn the cleavage specificity of a given class of proteases.
homepage_url: https://github.com/fabriziocosta/eden
long_description: |
    This tool can learn the cleavage specificity of a given class of protease.
    In a second step this can be used to predict proteases given a cleavage site.
    The method assumes that the candidate cleavage point is between the two amino acids adjacent to the central position.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/protease_prediction
type: unrestricted
categories:
    - Sequence Analysis
    - Proteomics
