name: sed_wrapper
owner: bgruening
description: Manipulate your data with the sed command line tool.
homepage_url: https://github.com/bgruening/galaxytools/tree/master/tools/sed
long_description: |
  Changes every line of a text file according to a given regular expression.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/sed
type: unrestricted
categories:
- Text Manipulation
