name: htseq_clip
owner: rnateam
description: |
  htseq-clip is a toolset for the analysis of eCLIP/iCLIP datasets
homepage_url: https://github.com/EMBL-Hentze-group/htseq-clip
long_description:
  htseq-clip is a toolset for the analysis of eCLIP/iCLIP datasets. 
  It can be used to generate files necessary for data analysis using 
  the companion R/Bioconductor package DEWSeq.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/rna_tools/htseq-clip
type: unrestricted
categories:
- Sequence Analysis
- RNA
- CLIP-seq
