categories: [RNA]
description: Produces an explicit sparse feature encoding and copmutes global feature
  index and returns top dense sets.
long_description: Integer code for the invariant graph encoding is used as a feature
  indicator. In this way,the integer associated to each feature (i.e. each pair or
  neighborhood subgraphs of radius r whose roots are at distance d) can be interpreted
  as the feature key and the (normalized) count of occurrences as its value. Also
  copmutes global feature index and returns top dense sets.The candidate clusters
  are chosen as the top ranking neighborhoods provided that the size of their overlap
  is below a specified threshold.
name: graphclust_nspdk
owner: rnateam
remote_repository_url: https://github.com/eteriSokhoyan/galaxytools/tree/branchForIterations/tools/GraphClust/NSPDK
