name: plotly_regression_performance_plots
owner: bgruening
description: performance plots for regression problems
homepage_url: http://scikit-learn.org/stable/supervised_learning.html#supervised-learning
long_description: |
  The tool creates three plots to measure the performance of a machine learning regression models on three metrics. 
  The metrics include: true vs predicted curves, scatter plot of true vs predicted values and a residual plot.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/plotly_regression_performance_plots
type: unrestricted
categories:
  - Visualization
