name: nastiseq
owner: rnateam
description: A method to identify cis-NATs using ssRNA-seq
homepage_url: https://ohlerlab.mdc-berlin.de/software/NASTIseq_104/
long_description: |
    To identify cis-NATs using ssRNA-seq, we developed a new computational
    method based on model comparison that incorporates the inherent variable
    efficiency of generating perfectly strand-specific libraries.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/rna_tools/nastiseq
type: unrestricted
categories:
- RNA
