name: molecule_to_gspan
owner: bgruening
description: converter
homepage_url: https://github.com/bgruening/galaxytools/tree/master/tools/molecule2gspan
long_description: |
  That converter will convert arbitratry molecule files to the gSpan format.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/molecule2gspan
type: unrestricted
categories:
- Convert Formats
