name: psortb
owner: bgruening
description: PSORTb — protein subcellular localization prediction for prokaryotes
long_description: |
  Galaxy wrapper for PSORTb, a tool that predicts the subcellular
  localization of bacterial and archaeal proteins. The tool supports
  Gram-positive, Gram-negative, and Archaea models.

homepage_url: https://psort.org/
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/psortb
type: unrestricted
categories:
  - Proteomics
  - Sequence Analysis

