categories:
- Computational chemistry
description: Mordred is a molecular descriptor calculator.
long_description: |
  Mordred is a descriptor-calculation software application that can calculate more than 1800 two- and three-dimensional descriptors.
  
  Home page: https://github.com/mordred-descriptor/mordred
  License: BSD

homepage_url: https://github.com/mordred-descriptor/mordred
name: mordred
owner: bgruening
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/chemicaltoolbox/mordred
type: unrestricted
maintainers:
  - simonbray
