name: fractal
owner: bgruening
categories:
  - Imaging
description: fractal task wrappers
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for fractal tasks {{ tool_name }}."
suite:
  name: "fractal"
  description: "A suite of tools that brings the fractal tasks into Galaxy."
  long_description: |
      a collection of ready-to-use tasks for processing bioimaging data. These tasks include OME-Zarr conversion, image registration, segmentation, and measurements.