name: wordcloud
owner: bgruening
description: A little word cloud generator in Python.
long_description: |
  The wordcloud library allows you to create word clouds from text data.
  It is highly customizable and can generate word clouds in various shapes and colors.
  The wordcloud library is available as an open-source project on GitHub.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/wordcloud
homepage_url: https://github.com/amueller/word_cloud
type:
categories:
  - Visualization
