name: pathoscope
owner: bgruening
categories:
  - Metagenomics
description: Species identification and strain attribution with unassembled sequencing data.
homepage_url: https://github.com/PathoScope/PathoScope
long_description: |
  PathoScope is a pipeline to rapidly and accurately remove host contamination, isolate microbial reads, and identify potential disease-causing pathogens.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/pathoscope
type: unrestricted
