name: imagej2_analyze_particles_binary
owner: iuc
description: |
  Contains a tool that wraps the ImageJ2 Analyze Particles command, with options,
  for binary images.
homepage_url: http://rsbweb.nih.gov/ij/docs/guide/146-29.html
long_description: |
  Analyzes the particles in a segmented binary image, providing information about
  each particle in the image.
remote_repository_url:
type: unrestricted
categories:
- Imaging
