name: uniprot_id_mapping
owner: bgruening
description: UniProt ID mapping and sequence retrieval
homepage_url: https://github.com/jdrudolph/uniprot
long_description: |
  UniProt ID mapping and sequence retrieval
  - map map a list of ids from one format onto another using uniprots mapping api
  - retrieve request entries by uniprot acc using batch retrieval
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/uniprot_id_mapping
type: unrestricted
categories:
- Proteomics
- Sequence Analysis
