name: data_manager_sylph_database
owner: bgruening
description: "Download pre-built databases for sylph"
homepage_url: "https://github.com/bluenote-1577/sylph"
long_description: |
    Download pre-built databases that have associated taxonomies that sylph can utilize for metagenomic profiling and incorporating taxonomy into sylph.
remote_repository_url: "https://github.com/bgruening/galaxytools/tree/master/data_managers/data_manager_sylph_database"
type: unrestricted
categories:
- Data Managers