name: pileometh
owner: bgruening
description: A tool for processing bisulfite sequencing alignments
homepage_url: https://github.com/dpryan79/PileOMeth
long_description: |
    PileOMeth (a temporary name derived due to it using a PILEup to extract METHylation metrics) 
    will process a coordinate-sorted and indexed BAM or CRAM file containing some form of BS-seq 
    alignments and extract per-base methylation metrics from them.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/pileometh
type: unrestricted
categories:
- Sequence Analysis
