name: bg_statistical_hypothesis_testing
owner: bgruening
categories:
  - Statistics
description: Tool for computing statistical tests.
long_description: |
  This tool make use of scipy and numpy, and contains large number of probability distributions, summary and frequency statistics, correlation functions and statistical tests
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/statistics
homepage_url: https://github.com/bgruening/galaxytools/tree/master/tools/statistics
type: unrestricted
