name: imagej2_analyze_skeleton
owner: iuc
description: |
  Contains a tool that tags all pixel/voxels in a skeleton image and then counts all
  its junctions, triple and quadruple points and branches, and measures their average
  and maximum length.
homepage_url: http://imagejdocu.tudor.lu/doku.php?id=plugin:analysis:analyzeskeleton:start
long_description: |
  This tool tags all pixel/voxels in a skeleton image and then counts all its junctions,
  triple and quadruple points and branches, and measures their average and maximum length.
  The "Skeletonize images" tool produces skeleton images that can be used as input to this
  tool.
remote_repository_url:
type: unrestricted
categories:
- Imaging
