name: 10x_bamtofastq
owner: bgruening
description: Converts 10x Genomics BAM to FASTQ
homepage_url: https://github.com/10XGenomics/bamtofastq
long_description: |
  Tool for converting 10x BAMs produced by Cell Ranger, Space Ranger, Cell Ranger ATAC, Cell Ranger DNA, and Long Ranger back to FASTQ files that can be used as inputs to re-run analysis. AUGUSTUS is a program that predicts genes in eukaryotic genomic sequences.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/10x_bamtofastq
type: unrestricted
categories:
- Convert Formats
