categories:
  - Computational chemistry
description: Calculate the box parameters for an AutoDock Vina job
long_description: |
    Calculate the box parameters for an AutoDock Vina job from an input mol file (confounding box)
    Home page: http://vina.scripps.edu/
    License: Apache 2.0
homepage_url: http://vina.scripps.edu/
name: autodock_vina_prepare_box
owner: bgruening
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/chemicaltoolbox/autodock_vina
type: unrestricted
maintainers:
  - simonbray
