name: wtdbg
owner: bgruening
categories:
- Nanopore
description: WTDBG is a fuzzy Bruijn graph (FBG) approach to long noisy reads assembly.
homepage_url: https://github.com/ruanjue/wtdbg-1.2.8
long_description: |
  WTDBG is a fuzzy Bruijn graph (FBG) approach to long noisy reads assembly.
  A challenge in assembling long noisy reads from third generation sequencing (TGS) is reducing its requirement of computing resource, especially for large genomes. To address this issue, I developed a novel sequence alignment algorithm and a new assembly graph for efficiently assembling large genomes using TGS data.


remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/wtdbg
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "WTDBG tool: {{ tool_name }}"
suite:
  name: "suite_wtdbg"
  description: "WTDBG software package"
  type: repository_suite_definition
