name: plotly_ml_performance_plots
owner: bgruening
description: performance plots for machine learning problems
homepage_url: http://scikit-learn.org/stable/modules/classes.html#module-sklearn.metrics
long_description: |
  The tool creates three plots to measure the performance of a machine learning trained model based on multiple metrics. 
  The metrics include: confusion matrix and precision, recall, F-score and area under the ROC curve.
  http://scikit-learn.org/stable/modules/generated/sklearn.metrics.confusion_matrix.html
  http://scikit-learn.org/stable/modules/generated/sklearn.metrics.precision_recall_fscore_support.html
  http://scikit-learn.org/stable/modules/generated/sklearn.metrics.roc_curve.html
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/plotly_ml_performance_plots
type: unrestricted
categories:
  - Visualization
