categories:
- Computational chemistry
description: Python library for accessing the ChEMBL database 
long_description: |
    This is the only official Python client library developed 
    and supported by ChEMBL group. Python 2 and 3 compatible.
    The library helps accessing ChEMBL data and cheminformatics 
    tools from Python. You don't need to know how to write SQL. 
    You don't need to know how to interact with REST APIs. 
    You don't need to compile or install any cheminformatics 
    frameworks. Results are cached.

homepage_url: https://github.com/chembl/chembl_webresource_client
name: chembl
owner: bgruening
remote_repository_url: https://github.com/chembl/chembl_webresource_client
type: unrestricted
