name: whisper
owner: bgruening
description: Transcribe audio or video files to text using the OpenAI Whisper.
long_description: |
  Transcribe audio or video files to text using the OpenAI Whisper.
  The OpenAI Whisper is a state-of-the-art speech-to-text model that can transcribe
  audio and video files with high accuracy. It supports a wide range of languages
  and can transcribe audio files with multiple speakers. The OpenAI Whisper is
  based on the GPT-3 model and is available as an open-source project on GitHub.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/whisper
type:
categories:
  - Machine Learning
maintainers:
  - itisalirh
