name: graphicsmagick
owner: bgruening
description: Contains tools based on GraphicsMagick
homepage_url: http://www.graphicsmagick.org
long_description: |
  GraphicsMagick is the swiss army knife of image processing.
  Comprised of 265K physical lines (according to David A. Wheeler's SLOCCount) of source code
  in the base package (or 1,220K including 3rd party libraries) it provides a robust and efficient
  collection of tools and libraries which support reading, writing, and manipulating an
  image in over 88 major formats including important formats like DPX, GIF, JPEG, JPEG-2000, PNG, PDF, PNM, and TIFF.

remote_repository_url: https://github.com/bgruening/galaxytools/new/gm/tools/image_processing/image_processing/
type: unrestricted
categories:
  - Imaging
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for the GraphicsMagic suite: {{ tool_name }}"
suite:
  name: "graphicsmagick_suite"
  description: Contains tools based on GraphicsMagick
  long_description: |
    GraphicsMagick is the swiss army knife of image processing.
    Comprised of 265K physical lines (according to David A. Wheeler's SLOCCount) of source code
    in the base package (or 1,220K including 3rd party libraries) it provides a robust and efficient
    collection of tools and libraries which support reading, writing, and manipulating an
    image in over 88 major formats including important formats like DPX, GIF, JPEG, JPEG-2000, PNG, PDF, PNM, and TIFF.
