name: cellprofiler
owner: bgruening
categories:
  - Imaging
description: cellProfiler wrapper
homepage_url: https://github.com/CellProfiler
long_description: |
  CellProfiler is a free open-source software designed to enable biologists without training in computer 
  vision or programming to quantitatively measure phenotypes from thousands of images automatically.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for cellProfiler moudule {{ tool_name }}."
suite:
  name: "cellprofiler"
  description: "A suite of tools that brings the cellProfiler project into Galaxy."
  long_description: |
      cellProfiler is free, open-source software for quantitative analysis of biological images
