name: package_javabridge_1_0_11
owner: iuc
description: Contains a tool dependency definition that downloads and extracts version
  1.0.11 of Javabridge.
homepage_url: http://pythonhosted.org/javabridge/
long_description: |
  The javabridge Python package makes it easy to start a Java virtual machine (JVM) from Python and interact with it.
  Python code can interact with the JVM using a low-level API or a more convenient high-level API.
  remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/packages/package_javabridge_1_0_11
type: tool_dependency_definition
categories:
  - Tool Dependency Packages
