categories:
- Computational chemistry
description: Protein pocket detection algorithm based on Voronoi tessellation
long_description: |
    The fpocket suite of programs is a very fast open source 
    protein pocket detection algorithm based on Voronoi tessellation. 
    The platform is suited for the scientific community willing 
    to develop new scoring functions and extract pocket descriptors 
    on a large scale level.
    
homepage_url: https://github.com/Discngine/fpocket/
name: fpocket
owner: bgruening
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/chemicaltoolbox/fpocket/
type: unrestricted
