name: mcl
owner: bgruening
description: Markov Cluster Algorithm
homepage_url: http://micans.org/mcl/
long_description: |
  The MCL algorithm is short for the Markov Cluster Algorithm, a fast and scalable unsupervised cluster algorithm 
  for graphs (also known as networks) based on simulation of (stochastic) flow in graphs. http://micans.org/mcl/
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/mcl
type: unrestricted
categories:
- Sequence Analysis
- Metagenomics
