categories:
- Visualization
description: |
    Plotting tool for long read sequencing data and alignments
long_description: |
    Nanoplot is a package for plotting various aspects of Nanopore
    sequencing data (fastq) and alignments (bam). It is part of the
    NanoPack tool suite for visualizing and processing long read
    sequencing data.
name: nanoplot
owner: bgruening
remote_repository_url: "https://github.com/bgruening/galaxytools/tree/master/tools/nanoplot"
homepage_url: "https://github.com/wdecoster/NanoPlot"
type: unrestricted
