owner: bgruening
name: protein_properties
description: Calculation of various properties from given protein sequences
long_description: |
  This tool will calculate several properties for each given input sequence.

remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/protein_properties
type: unrestricted
categories:
- Sequence Analysis
