category: ToolFactory generated Tools
description: A toolkit to predict antimicrobial peptides from protein sequences on
  a genome-wide scale.
name: ampir
owner: toolfactory
synopsis: A toolkit to predict antimicrobial peptides from protein sequences on a
  genome-wide scale.
type: unrestricted
