package:
  name: ribotaper
  version: "1.3.1"

source:
  path: /home/ydilimu/Downloads/ribotaper-1.3.1
  url:
  md5:
build:
  number: 1

requirements:
  build:
    - bedtools
    - samtools
    - r-iterators
    - r-foreach
    - r-domc
    - r-ade4
    - r-seqinr
    - r-multitaper
    - r-xnomial
  run:
    - bedtools
    - samtools
    - r-iterators
    - r-foreach
    - r-domc
    - r-ade4
    - r-seqinr
    - r-multitaper
    - r-xnomial

test:
  commands:
    - Ribotaper.sh 2>&1  | grep Usage > /dev/null
    - create_annotations_files.bash 2>&1  | grep Usage > /dev/null
    - create_metaplots.bash 2>&1  | grep Usage > /dev/null

about:
  home: https://ohlerlab.mdc-berlin.de/software/RiboTaper_126/
  license: GPL
  summary: 'RiboTaper is a new analysis pipeline for
  Ribosome Profiling (Ribo-seq) experiments,
  which exploits the triplet periodicity of
  ribosomal footprints to call translated regions.'
