name: imagej2_sharpen
owner: iuc
description: |
  Contains a tool that wraps the ImageJ2 Sharpen command.
homepage_url: http://rsb.info.nih.gov/ij/docs/menus/process.html
long_description: |
  Contains a tool that increases contrast and accentuates detail in the image,
  but may also accentuate noise.
remote_repository_url:
type: unrestricted
categories:
- Imaging
