categories:
- Computational chemistry
description: rDock dcoking program plus assicated utilities.
long_description: |
  rDock is a molecular docking program for deteremining docked poses of ligands in a target (protein) active site.
  Home page: http://rdock.sourceforge.net/
  License: LGPL Version 3.0

homepage_url: http://rdock.sourceforge.net/
name: rdock
owner: bgruening
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/chemicaltoolbox/rdock
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "{{ tool_name }} tool"
suite:
  name: suite_rdock
  description: |
    rDock is a fast and versatile Open Source docking program that can be used to dock small molecules against proteins
    and nucleic acids. It is designed for High Throughput Virtual Screening (HTVS) campaigns and Binding Mode prediction
    studies.

