categories: [RNA]
description: Determines consensus motives for sequences.
long_description: At first it converts CLUSTAL format files to STOCKHOLM format. Then
  using CMFinder determines consensus motives for sequences.
name: graphclust_cmfinder
owner: rnateam
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/GraphClust/CMFinder
