name: cool_to_hic
owner: fubar2
categories:
  - Sequence Analysis
description: Convert cool format to binary hic
homepage_url: https://github.com/vgl-hub/gfastats
long_description: Uses hictk
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/cool_to_hic
type: unrestricted
