name: instagraal
owner: bgruening
categories:
- Assembly
description: Large genome reassembly based on Hi-C data
homepage_url: https://github.com/koszullab/instaGRAAL
long_description: |
  Large genome reassembly based on Hi-C data
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/instagraal
type: unrestricted
