categories:
- Computational chemistry
description: OpenDUck, an open-source implementation of the original DUck method, using OpenMM and AmberTools
long_description: |
  OpenDUck, an open-source implementation of the original DUck method, using OpenMM and AmberTools

homepage_url: https://github.com/xchem/duck
name: openduck
owner: bgruening
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/chemicaltoolbox/openduck
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "{{ tool_name }} tool from OpenDUck"
suite:
  name: suite_openduck
  description: OpenDUck, an open-source implementation of the original DUck method, using OpenMM and AmberTools
