name: mlocarna
owner: rnateam
description: "LocARNA - Multiple Alignment and Folding of RNAs"
homepage_url: http://www.bioinf.uni-freiburg.de/Software/LocARNA/
long_description: |
    The LocARNA package comprises tools for fast, high-quality pairwise
    and multiple alignment of RNA sequences, while inferring unknown
    structure; this is accomplished by simultaneous folding and alignment
    based on sequence and structure features of the RNAs.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/rna_tools/mlocarna
type: unrestricted
categories:
  - RNA
