name: stats_perf_tool
owner: bgruening
description: suitable for boolean classification problems 
homepage_url: http://osmot.cs.cornell.edu/kddcup/software.html
long_description: |
  Perf calculates a variety of performance metrics suitable for boolean classification problems. 
  Metrics include: accuracy, root-mean-squared-error, cross-entropy, precision, recall, precision/recall 
  break-even point and F-score, area under the ROC curve, lift, weighted cost, top 1, top 10, rank of lowest 
  positive case, q-score, several measures of probability calibration, etc.
  http://osmot.cs.cornell.edu/kddcup/software.html
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/perf
type: unrestricted
categories:
