name: rbpbench
owner: rnateam
description: Evaluate CLIP-seq and other genomic region data using a comprehensive collection of RBP binding motifs
homepage_url: https://github.com/michauhl/RBPBench
long_description: |
  RBPBench is multi-function tool to evaluate CLIP-seq and other genomic region 
  data using a comprehensive collection of known RBP binding motifs. RBPBench can 
  be used for a variety of purposes, from RBP motif search (database or user-supplied 
  RBPs) in genomic regions, over motif co-occurrence analysis, to benchmarking 
  CLIP-seq peak caller methods as well as comparisons across cell types and 
  CLIP-seq protocols.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/rna_tools/rbpbench
type: unrestricted
categories:
- Sequence Analysis
- RNA
- CLIP-seq
