# Keep the default tracking settings, but constrain candidate ceilings.
entry_classes:
  - Word
  - Phone
target_tier: Phone
target_labels: "[AEIOU]"
min_duration: 0.05
min_max_formant: 5000
max_max_formant: 5100
n_formants: 3
nstep: 2
window_length: 0.025
time_step: 0.002
smoother:
  method: dct_smooth_regression
  order: 5
