name: imagej2_find_edges
owner: iuc
description: |
  Contains a tool that wraps the ImageJ2 Find Edges command.
homepage_url: http://rsb.info.nih.gov/ij/docs/menus/process.html
long_description: |
  Contains a tool that uses a Sobel edge detector to highlight sharp changes in
  intensity in the active image.
remote_repository_url:
type: unrestricted
categories:
- Imaging
