categories:
  - Computational chemistry
description: Download PDB files
long_description: |
    Download a protein structure in PDB format from the Protein Data Bank using its four-letter accession code.
name: get_pdb
owner: bgruening
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/chemicaltoolbox/data_source/get_pdb
type: unrestricted
