name: bamhash
owner: bgruening
description: Hash BAM and FASTQ files to verify data integrity
homepage_url: https://github.com/DecodeGenetics/BamHash
long_description: |
    For each pair of reads in a BAM or FASTQ file we compute a hash value composed of the readname,
    whether it is first or last in pair, sequence and quality value. All the hash values are summed
    up so the result is independent of the ordering within the files. The result can be compared to
    verify that the pair of FASTQ files contain the same read information as the aligned BAM file.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/bamhash
type: unrestricted
categories:
- Sequence Analysis
