name: rcas
owner: rnateam
description: RNA Centric Annotation System that provides intuitive reports and publication ready graphics.
homepage_url: git@github.com:BIMSBbioinfo/RCAS.git
long_description: |
  RCAS takes input peak intervals in BED foramt from clip-seq data and
  automatically generates distributions of annotation features,
  detected motifs, GO-term enrichment, pathway enrichment and genomic coverage.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/rna_tools/rcas/
type: unrestricted
categories:
- RNA
