name: rcas
owner: rnateam
description: RCAS (RNA Centric Annotation System) for functional analysis of transcriptome-wide regions detected by high-throughput experiments
homepage_url: https://github.com/BIMSBbioinfo/RCAS
long_description: |
  RCAS takes input peak intervals in BED format from CLIP-seq data and
  automatically annotates features, provides information about genomic coverage, 
  detects motifs, and runs GO term and gene set enrichment analysis. RCAS can perform 
  a single dataset analysis as well as a comparative multi dataset analysis.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/rna_tools/rcas/
type: unrestricted
categories:
- RNA
