name: 3dtrees_potree
owner: bgruening
description: generates octree LOD structure from point clouds
homepage_url: https://github.com/3dTrees-earth/3dtrees_potree
long_description: |
  generates octree LOD structure from point clouds
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/3dtrees_potree
type: unrestricted
categories:
- Geo Science
