categories:
- Computational chemistry
description: Software for protein-compound docking - the prepare ligand step
long_description: |
    AutoDock Vina is an open-source program for doing molecular docking.
    Home page: http://vina.scripps.edu/
    License: Apache 2.0
homepage_url: http://vina.scripps.edu/
name: autodock_vina_prepare_ligand
owner: bgruening
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/chemicaltoolbox/autodock_vina
type: unrestricted
maintainers:
  - simonbray
