name: imagej2_shadows
owner: iuc
description: |
  Contains a tool that wraps the various ImageJ2 Shadows commands (East, North,
  Northeast, etc.).
homepage_url: http://rsbweb.nih.gov/ij/docs/guide/146-29.html
long_description: |
  Contains a tool that produces a shadow effect, with light appearing to come
  from a direction corresponding to the command name (East, North, Northeast,
  Northwest, South, Southeast, Southwest and West). The commands use Convolve
  3 × 3, ImageJ’s 3 × 3 convolution function.
remote_repository_url:
type: unrestricted
categories:
- Imaging
