name: sylph
owner: bgruening
description: sylph - fast and precise species-level metagenomic profiling with ANIs
long_description: sylph is a program that performs ultrafast (1) ANI querying or (2) metagenomic profiling for metagenomic shotgun samples.
homepage_url: https://github.com/bluenote-1577/sylph
remote_repository_url: https://github.com/bgruening/galaxytools/main/tools/sylph
categories:
  - Metagenomics
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "{{ tool_name }} from the sylph suite"

