categories:
  - Sequence Analysis
description: MappingQC is a tool to easily generate reports of the quality of the mapping of ribosome profiling data
homepage_url: https://github.com/Biobix/mQC
name: mqc
owner: rnateam
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/rna_tools/mqc
