categories:
  - Sequence Analysis
description: MappingQC is a tool to easily generate reports of the quality of the mapping of ribosome profiling data
long_description: |
  MappingQC is a tool to easily generate some figures which give a nice overview of the quality of
  the mapping of ribosome profiling data. More specific, it gives an overview of the P site offset calculation,
  the gene distribution and the metagenic classification. Furthermore, MappingQC does a thorough analysis of
  the triplet periodicity and the linked triplet phase (typical for ribosome profiling) in the canonical
  transcript of your data. Especially, the link between the phase distribution and the RPF length,
  the relative sequence position and the triplet identity are taken into account.
homepage_url: https://github.com/Biobix/mQC
name: mqc
owner: rnateam
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/rna_tools/mqc
