name: simorgh
owner: bgruening
description: Apo-State and Cryptic Ligand Binding Site Prediction
homepage_url: https://github.com/amisteromid/SIMORGH
long_description: |
  SIMORGH is a deep learning-based method for predicting apo-state and cryptic ligand binding sites in proteins. It leverages SE(3) equivariant neural networks to accurately identify potential binding pockets. This tool is particularly useful for drug discovery, where understanding the dynamic nature of protein structures is crucial.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/simorgh
type: unrestricted
categories:
  - Computational chemistry
  - Molecular Dynamics
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for {{ tool_name }}."