name: rnalien
owner: rnateam
description: RNAlien unsupervized RNA family model construction
long_description: |
  Determining  the  function  of  a  non-coding RNA
  requires  costly  and  time-consuming  wet-lab  experiments.
  For  this  reason,  computational  methods
  which  ascertain  the  homology  of  a  sequence  and
  thereby deduce functionality and family membership
  are often exploited. In this fashion, newly sequenced
  genomes can be annotated in a completely computa-
  tional way. Covariance models are commonly used to
  assign novel RNA sequences to a known RNA family.
  However, to construct such models several examples
  of  the  family  have  to  be  already  known.  Moreover,
  model  building  is  the  work  of  experts  who  manually edit the necessary
  RNA alignment and consensus structure. Our method,
  RNAlien, starting from a single input sequence collects potential family
  member sequences by multiple iterations of homology  search.
  RNA family  models  are  fully  automatically constructed
  for the found sequences. We have tested our method on a subset of the
  Rfam RNA family  database. RNAlien models  are  a  starting  point
  to  construct  models  of  comparable  sensitivity  and
  specificity to manually curated ones from the Rfam database.
  RNAlien Tool and web server are available at
homepage_url: http://rna.tbi.univie.ac.at/rnalien/
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/rna_tools/rnalien
type: unrestricted
categories:
  - RNA
  - Sequence Analysis
