description: netboxr enables automated discovery of biological process modules by network analysis
long_description: |
  The NetBox algorithm identifies candidate cancer-related functional modules using a data-driven, network-based approach that combines prior knowledge with a network clustering algorithm. The network modules are derived de novo, and can be used to identify new functional gene groups that cross the boundaries of curated gene sets.
name: netboxr
owner: bgruening
categories:
  - Systems Biology
