categories:
- Computational chemistry
description: Generate 3D descriptors for a ligand conformer
long_description: |
    Generate 3D descriptors for a ligand conformer, based on predicting
    the electrostatic potential (ESP) using a deep neural network, and
    computing spherical harmonic coefficients.
    
homepage_url: https://github.com/rwmontalvao/SHCoeffsDev
name: lirasearch
owner: bgruening
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/chemicaltoolbox/lirasearch/
type: unrestricted
maintainers:
  - simonbray
