name: inforna
owner: rnateam
description: INFO-RNA is a service for the design of RNA sequences that fold into a given pseudo-knot free RNA secondary structure.
homepage_url: http://rna.informatik.uni-freiburg.de/INFORNA/Input.jsp
long_description: INFO-RNA is a service for the design of RNA sequences that fold into a given pseudo-knot free RNA secondary structure. http://rna.informatik.uni-freiburg.de/INFORNA/Input.jsp
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/rna_tools/inforna
type: unrestricted
categories:
- RNA
