name: sshmm
owner: iuc
description: |
  ssHMM is an RNA sequence-structure motif finder for RNA-binding protein data, such as CLIP-Seq data
homepage_url: https://github.molgen.mpg.de/heller/ssHMM
long_description:
    ssHMM is an RNA motif finder that recovers sequence-structure motifs from RNA-binding protein data, such as CLIP-Seq data. The tool input consists of a BED file with genomic binding regions and the corresponding genome reference FASTA file. For structure prediction, the user can select between RNAshapes and RNAstructures. Advanced parameters can be set for both the preprocessing and the training stage.
    The output consists of a graph showing the found sequence motifs for the 5 structural contexts multiloop, hairpin, stem, internal loop, and exterior loop (output in .png format). The height of the nucleotides corresponds to their emission probabilities, while the thickness of the arrows corresponds to their transition probabilities. Additional files (intermediate, logo, model, raw) can be selected for output in the "Output options" section.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/rna_tools/sshmm/
type: unrestricted
categories:
- Sequence Analysis
- RNA
