categories:
- Computational chemistry
description: Chemfp tools for working with cheminformatics fingerprints in the FPS format
long_description: |
    Chemfp is a set of command-line tools and a Python library for fingerprint generation
    and high-performance similarity search. Chemfp supports the FPS exchange format for fingerprint data,
    so if want something beyond the OpenEye, Open Babel and RDKit fingerprints that chemfp
    supports then you can write your own FPS files and still use the fast Tanimoto search tool.
    It also supports the FPB binary format for fast loading, which is handy fast web server reloads and subsecond command-line searches.

    http://chemfp.com/
name: chemfp
owner: bgruening
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/chemicaltoolbox/chemfp
type: unrestricted
