name: glimmer_hmm
owner: bgruening
description: GlimmerHMM is a new gene finder based on a Generalized Hidden Markov Model (GHMM)
homepage_url: https://ccb.jhu.edu/software/glimmerhmm/
long_description: |
  GlimmerHMM is a new gene finder based on a Generalized Hidden Markov Model (GHMM). 
  Although the gene finder conforms to the overall mathematical framework of a GHMM, additionally it incorporates 
  splice site models adapted from the GeneSplicer program and a decision tree adapted from GlimmerM. 
  It also utilizes Interpolated Markov Models for the coding and noncoding models . Currently, GlimmerHMM's GHMM 
  structure includes introns of each phase, intergenic regions, and four types of exons 
  (initial, internal, final, and single).
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/glimmer_hmm
type: unrestricted
categories:
- Sequence Analysis
