name: sem_analysis
owner: bgruening
description: Scanning electron micrographs (SEM) fiber analysis using FIJI, DiameterJ and Auto-thresholding.
long_description: |
  The SEM Analysis tool segments fibers and measures their diameters, and pores with FIJI, DiameterJ and Auto-thresholding
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/sem_analysis
homepage_url: https://github.com/bgruening/galaxytools/tree/master/tools/sem_analysis
type:
categories:
  - Material Science
maintainers:
  anuprulez