name: 3dtrees_segmentanytree
owner: bgruening
description: forest instance segmentation
homepage_url: https://github.com/3dTrees-earth/3dtrees_sat
long_description: |
  Performs forest instance segmentation on point clouds using the SegmentAnyTree model.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/3dtrees_segmentanytree
type: unrestricted
categories:
- "Geo Science"
