name: glimmer3
owner: bgruening
description: This is the main program that makes gene predictions.
homepage_url: https://ccb.jhu.edu/software/glimmer/
long_description: This is the main program that makes gene predictions based on an interpolated context model (ICM).
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/glimmer3
type: unrestricted
categories:
- Sequence Analysis
