name: ketos_ocr
owner: bgruening
description: Wrapper Ketos, the model training part of the OCR system kraken
long_description: |
  Ketos is the model training part of the OCR system kraken. It is used to train models for historical and non-Latin script material.
type: unrestricted
categories:
  - Natural Language Processing
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/ketos_ocr
homepage_url: https://kraken.re/
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for HTR/OCR tool: {{ tool_name }}"
suite:
  name: "suite_ketos_ocr"
  description: Wrapper of the model training commands for the OCR system kraken
  long_description: |
    Ketos is the model training part of the OCR system kraken. It is used to train models for historical and non-Latin script material.