name: locarna
owner: rnateam

remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/rna_tools/locarna
homepage_url: http://www.bioinf.uni-freiburg.de/Software/LocARNA/
type: unrestricted
categories:
  - RNA

description: "LocARNA - A suite for multiple alignment and folding of RNAs"
long_description: |
    The LocARNA package comprises tools for fast, high-quality pairwise
    and multiple alignment of RNA sequences, while inferring unknown
    structure; this is accomplished by simultaneous folding and alignment
    based on sequence and structure features of the RNAs.


auto_tool_repositories:
    name_template: "{{ tool_id }}"
    description_template: "Wrapper for application {{ tool_name }} of the LocARNA suite"
    type: unrestricted

suite:
    name: "suite_locarna"
    description: "LocARNA - A suite for multiple alignment and folding of RNAs"
    long_description: |
        The LocARNA package comprises tools for fast, high-quality pairwise
        and multiple alignment of RNA sequences, while inferring unknown
        structure; this is accomplished by simultaneous folding and alignment
        based on sequence and structure features of the RNAs.
