name: pandas_rolling_window
owner: bgruening
description: Rolling window calculations
homepage_url: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rolling.html
long_description: |
  Rolling window calculations using the python pandas library.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/pandas_rolling_window
type: unrestricted
categories:
  - Statistics
