categories: [RNA]
description: This tool prepares files for locarna step.
long_description: This tool prepares files for locarna step.
name: graphclust_prepocessing_for_mlocarna
owner: rnateam
remote_repository_url: https://github.com/eteriSokhoyan/galaxytools/tree/branchForIterations/tools/GraphClust/PrepareForMlocarna
