name: dewseq
owner: rnateam
description: |
  DEWSeq is a sliding window based peak caller for eCLIP/iCLIP data
homepage_url: https://github.com/EMBL-Hentze-group/DEWSeq_analysis_helpers
long_description:
  DEWSeq is a sliding window approach for the analysis of differentially enriched 
  binding regions eCLIP or iCLIP next generation sequencing data.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/rna_tools/dewseq
type: unrestricted
categories:
- Sequence Analysis
- RNA
- CLIP-seq
