name: imagej2_binary_to_edm
owner: iuc
description: |
  Contains a tool that wraps ImageJ2 EDM plugin, restricting use to the "toEDM"
  method.
homepage_url: https://github.com/imagej/imagej1/blob/master/ij/plugin/filter/EDM.java
long_description: |
  Converts a binary image into a 8-bit grayscale Euclidean Distance Map (EDM). Each
  foreground (nonzero) pixel in the binary image is assigned a value equal to its
  distance from the nearest background (zero) pixel.
remote_repository_url:
type: unrestricted
categories:
- Imaging
