name: samtools_sort
owner: devteam
description: This tool uses the SAMTools toolkit to sort alignments by leftmost coordinates or read names.
homepage_url: http://samtools.sourceforge.net/samtools.shtml
long_description: |
  This tool uses the SAMTools toolkit to sort alignments by leftmost coordinates or read names.
  http://samtools.sourceforge.net/samtools.shtml
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/samtools_sort
type: unrestricted
categories:
- Sequence Analysis
