categories:
- Computational chemistry
description: rxDock dcoking program plus assicated utilities.
long_description: |
  rxDock is a molecular docking program for deteremining docked poses of ligands in a target (protein) active site.
  Home page: https://www.rxdock.org
  License: LGPL Version 3.0

homepage_url: https://www.rxdock.org
name: rxdock
owner: bgruening
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/chemicaltoolbox/rxdock
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "{{ tool_name }} tool"
suite:
  name: suite_rxdock
  description: |
    rxDock is a fast and versatile Open Source docking program that can be used to dock small molecules against proteins
    and nucleic acids. It is designed for High Throughput Virtual Screening (HTVS) campaigns and Binding Mode prediction
    studies.
