name: graphclust
owner: bgruening
description: GraphClust can be used for structural clustering of RNA sequences.
homepage_url: http://www.bioinf.uni-freiburg.de/Software/GraphClust/
long_description: |
  GraphClust can be used for structural clustering of RNA sequences. Especially it can be used for clustering 
  of very large dataset with thousands of RNAs.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/graphclust
type: unrestricted
categories:
- RNA
