name: tabicl
owner: bgruening
description: Tabular data prediction using TabICLv2.
long_description: The TabICLv2 is a state-of-the-art tabular data prediction model via in-context learning.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/tabular-prediction
homepage_url: https://github.com/bgruening/galaxytools/tree/master/tools/tabular-prediction
type:
categories:
  - Machine Learning
maintainers:
  anuprulez
