categories:
- Sequence Analysis
- Fasta Manipulation
description: Lighter is a kmer-based error correction method for whole genome sequencing data
long_description: |
    Lighter is a kmer-based error correction method for whole genome sequencing data
name: lighter
owner: bgruening
remote_repository_url: https://github.com/mourisl/Lighter
type: unrestricted
