name: pgchem
owner: bgruening
remote_repository_url: "https://github.com/bgruening/galaxytools/tree/master/chemicaltoolbox/pgchem"
homepage_url: "https://github.com/bgruening/galaxytools/tree/master/chemicaltoolbox/pgchem"
categories:
- Computational chemistry
description: "Tools for chemical database manipulation."
long_description: |
 "Tools for chemical database manipulation."
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "{{ tool_name }} tool from the bgchem Chemical Toolbox"
suite:
  name: suite_pgchem
  description: tools from the pgchem Chemical Toolbox.
  type: repository_suite_definition