name: ribotaper
owner: rnateam
description: A method for defining traslated ORFs using Ribosome Profiling data.
homepage_url: https://ohlerlab.mdc-berlin.de/software/RiboTaper_126/
long_description: |
  RiboTaper is a new analysis pipeline for Ribosome Profiling (Ribo-seq) experiments,
  which exploits the triplet periodicity of ribosomal footprints to call translated regions.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/rna_tools/ribotaper/
type: unrestricted
categories:
- RNA
