categories: [RNA]
description: Aggregate and filter alignment metrics of individual clusters, like the output of graphclust_align_cluster.
name: graphclust_aggregate_alignments
owner: rnateam
remote_repository_url: https://github.com/bgruening/galaxytools/tools/GraphClust/AggregateAlignments
