name: methylkit
owner: rnateam
description: A method for DNA methylation analysis and annotation from high-throughput bisulfite sequencing.
homepage_url: http://bioconductor.org/packages/release/bioc/html/methylKit.html
long_description: |
    methylKit is an R package for DNA methylation analysis and annotation
    from high-throughput bisulfite sequencing. The package is designed to deal with
    sequencing data from RRBS and its variants, but also target-capture methods and
    whole genome bisulfite sequencing. It also has functions to analyze base-pair
    resolution 5hmC data from experimental protocols such as oxBS-Seq and TAB-Seq.
    Perl is needed to read SAM files only.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/methylkit
type: unrestricted
categories:
- Epigenetics
