name: kinwalker
owner: rnateam
description: Kinwalker splits the folding process into a series of events where each event can either be a folding event or a transcription event.   
homepage_url: http://www.bioinf.uni-leipzig.de/Software/Kinwalker/
long_description: Kinwalker splits the folding process into a series of events where each event can either be a folding event or a transcription event. In each transcription event one base from the RNA sequence is appended to the already transcribed and (partially) folded subsequence. http://www.bioinf.uni-leipzig.de/Software/Kinwalker/
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/rna_tools/kinwalker
type: unrestricted
categories:
- RNA
