name: Wound healing scratch assay image analysis
owner: bgruening
categories:
  - Imaging
description: Tool to automate quantification of wound healing in high-throughput microscopy scratch assays
long_description: automated quantification of wound healing in high-throughput microscopy scratch assays.
homepage_url: https://git.embl.de/grp-cba/wound-healing-htm-screen
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "A Tool to automate quantification of wound healing in high-throughput microscopy scratch assays"
