name: data_manager_sortmerna_database_downloader
owner: rnateam
description: "SortMeRNA: a sequence analysis tool for filtering, mapping and clustering NGS reads"
homepage_url: "http://bioinfo.lifl.fr/RNA/sortmerna/"
long_description: |
  SortMeRNA is a software designed to rapidly filter ribosomal RNA fragments from 
  metatransriptomic data produced by next-generation sequencers.
remote_repository_url: "https://github.com/galaxyproject/tools-iuc/tree/master/data_managers/data_manager_sortmerna_database_downloader"
type: unrestricted
categories:
- Data Managers
