categories:
- Proteomics
description: OpenMS in version 2.0.
long_description: |
  OpenMS is an open-source software C++ library for LC-MS data management and analyses.
  It offers an infrastructure for the rapid development of mass spectrometry related software.
  OpenMS is free software available under the three clause BSD license and runs under Windows, MacOSX and Linux. 

  https://github.com/OpenMS/OpenMS
name: openms
owner: bgruening
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/openms
type: unrestricted
