categories:
- Computational chemistry
description: InformaticsMatters scripts for cheminformatics and computational chemistry.
long_description: |
  InformaticsMatters scripts for cheminformatics and computational chemistry.
  Home page: https://github.com/InformaticsMatters/pipelines/
  License: Apache 2.0

homepage_url: https://github.com/InformaticsMatters/pipelines/
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "{{ tool_name }} tool from im-pipelines"
suite:
  name: suite_im_pipelines
  description: InformaticsMatters scripts for cheminformatics and computational chemistry.
name: im_pipelines
owner: bgruening
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/chemicaltoolbox/im-pipelines
type: unrestricted
