owner: bgruening
name: bigwig_to_bedgraph
categories:
- Convert Formats
description: Convert from bigWig to bedGraph format
long_description: |
  Convert from bigWig to bedGraph format.

  http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/bigwig_to_bedgraph
type: unrestricted
