categories:
  - Computational chemistry
homepage_url: https://github.com/dan2097/opsin
name: opsin
owner: bgruening
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/chemicaltoolbox/opsin
type: unrestricted
repositories:
  opsin:
    description: OPSIN (Open Parser for Systematic IUPAC Nomenclature) IUPAC name-to-structure conversion
    long_description: |
      OPSIN is an Open Parser for Systematic IUPAC Nomenclature.
      This suite provides tools to convert IUPAC chemical names into machine-readable structures,
      including SMILES, CML, and InChI formats.
    include:
      - opsin.xml