name: chewtree
owner: bgruening
description: Builds phylogenetic trees from allelic profiles using ChewBBACA
homepage_url: https://github.com/B-UMMI/ChewBBACA
long_description: |
  ChewTree is part of the ChewBBACA suite. It builds phylogenetic trees from allelic profiles computed by ChewBBACA's AlleleCall algorithm.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/chewtree
type: unrestricted
categories:
- Phylogenetics
- Sequence Analysis
