name: imagej2_find_maxima
owner: iuc
description: |
  Contains a tool that wraps the ImageJ2 Find Maxima command.
homepage_url: http://rsb.info.nih.gov/ij/docs/menus/process.html
long_description: |
  Contains a tool that determines the local maxima in an image and creates a binary (mask-like)
  image of the same size with the maxima, or one segmented particle per maximum, marked.  For RGB
  images, maxima of luminance are selected with the luminance defined as the weighted or unweighted
  average of the colors depending on the "Scale when converting" and "Weighted RGB conversions"
  settings.
remote_repository_url:
type: unrestricted
categories:
- Imaging
