name: pgtools
owner: bgruening
description: tool suite for dealing with Postgresql databases from Galaxy's history

long_description: |
    The postgresql tools, are using a postgresql database in user-space.
    Databases are packed into a tarball and stored in the user-history.
    
    These tools are based on https://github.com/solidsnack/pglite to interact with postgresql in user-space.

categories:
    - Data Export
    - Data Source
remote_repository_url: https://github.com/bgruening/galaxytools/tools/pgtools
homepage_url: https://www.postgresql.org

auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Postgresql toolbox: {{ tool_name }}"
suite:
  name: "postgresql_suite"
  description: "A suite of Galaxy tools for dealing with Postgresql databases from Galaxy's history"
  
  long_description: |
    The postgresql tools, are using a postgresql database in user-space.
    Databases are packed into a tarball and stored in the user-history.
    
    These tools are based on https://github.com/solidsnack/pglite to interact with postgresql in user-space.
