categories:
- Computational chemistry
description: Calculates molecular descriptors and fingerprints.
long_description: |
  Calculates molecular descriptors and fingerprints. This tool calculates 1D, 2D and 3D descriptors and different types of fingerprints. 
  The descriptors and fingerprints are calculated using The Chemistry Development Kit with additional descriptors and fingerprints such as atom type electrotopological state descriptors, Crippen's logP and MR, extended topochemical atom (ETA) descriptors, McGowan volume, molecular linear free energy relation descriptors, ring counts, count of chemical substructures identified by Laggner, and binary fingerprints and count of chemical substructures.

  License: BSD

homepage_url: http://www.yapcwsoft.com/dd/padeldescriptor/
name: padel
owner: bgruening
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/chemicaltoolbox/PaDEL
type: unrestricted
