name: mirdeep2_quantifier
owner: rnateam
description: MiRDeep2 is a software package for identification of novel and known miRNAs in deep sequencing data.
homepage_url: https://www.mdc-berlin.de/8551903/en/
long_description: MiRDeep2 is a software package for identification of novel and known miRNAs in deep sequencing data. Furthermore, it can be used for miRNA expression profiling across samples.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/mirdeep2/mirdeep2_quantifier
type: unrestricted
categories:
- RNA
