
categories:
- Sequence Analysis
- RNA
- Transcriptomics
homepage_url: https://github.com/COMBINE-lab/salmon
description: Salmon is a wicked-fast program to produce a highly-accurate, transcript-level quantification estimates from RNA-seq and single-cell data.
long_description: |
  Salmon is a wicked-fast program to produce a highly-accurate, transcript-level quantification estimates from RNA-seq data. Salmon achieves
   is accuracy and speed via a number of different innovations, including the use of quasi-mapping (accurate but fast-to-compute proxies for
   traditional read alignments), and massively-parallel stochastic collapsed variational inference. The result is a versatile tool that fits
   nicely into many differnt pipelines. For example, you can choose to make use of our quasi-mapping algorithm by providing Salmon with raw
   sequencing reads, or, if it is more convenient, you can provide Salmon with regular alignments (e.g. an unsorted BAM file produced with
   your favorite aligner), and it will use the same wicked-fast, state-of-the-art inference algorithm to estimate transcript-level abundances
   for your experiment. Alevin adds to this functionality with a fast end-to-end pipeline to process droplet-based single-cell RNA sequencing
   data, performing cell barcode detection, read mapping, unique molecular identifier (UMI) deduplication, gene count estimation, and cell
   barcode whitelisting.
owner: bgruening
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/salmon
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "{{ tool_name }} function from the salmon"
suite:
  name: suite_salmon
  description: Salmon is a wicked-fast program to produce a highly-accurate, transcript-level quantification estimates from RNA-seq and single-cell data.
  type: repository_suite_definition
