name: 3dtrees_standardization
owner: bgruening
description: laz file checks and standardization.
homepage_url: https://github.com/3dTrees-earth/3dtrees-pc-standard
long_description: |
  Validates and standardizes LiDAR point cloud files (.laz format) through 8 comprehensive checks including: Basic LAS validation (point count, bounding box), Spatial extent and Z-range validation, Point density checks (>500 pts/m²), CRS validation and transformation capability, Point data format downgrading (to format ≤7), Geographic validation (centroid on land).
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/3Dtrees_standardization
type: unrestricted
categories:
- "Geo Science"
