name: pileometh
owner: bgruening
description: A tool for processing bisulfite sequencing alignments
homepage_url: https://github.com/dpryan79/MethylDackel
long_description: |
    MethylDackel will process a coordinate-sorted and indexed BAM or CRAM file containing some form of BS-seq 
    alignments and extract per-base methylation metrics from them.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/methyldackel
type: unrestricted
categories:
- Sequence Analysis
