categories:
- RNA
description: Compute secondary structures of RNA
name: rnashapes
owner: rnateam
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/rna_tools/rna_shapes
type: unrestricted
