name: atactk_trim_adapters
owner: rnateam
description: Trim adapters from paired-end HTS reads.
homepage_url: https://github.com/ParkerLab/atactk/
long_description: |
    The trim_adapters utility aligns paired reads to each other
    and trims off sequence outside the alignment.
remote_repository_url: https://github.com/bgruening/galaxytools/blob/master/tools/trim_adapters
type: unrestricted
categories:
  - Fastq Manipulation
