name: music
owner: rnateam
description: An algorithm for identification of enriched regions at multiple scales in the read depth signals from ChIP-Seq $
homepage_url: http://music.gersteinlab.org
long_description: MUSIC allows analyzing the scale length spectrum of ChIP-Seq datasets and also selecting a user specific slice in the scale length spectrum with custom granularity and generates the enriched regions at each length scale. MUSIC does not strictly require a control experiment (for example mock IP, input DNA) to be performed. It is, however, strongly advised to generate control datasets matching the sample of interest.
remote_repository_url: https://github.com/gersteinlab/MUSIC
type: unrestricted
categories:
- RNA
