name: imagej2_create_image
owner: iuc
description: Contains a tool that creates a new image of a selected type, size, depth and format.
homepage_url:
long_description:
remote_repository_url:
type: unrestricted
categories:
- Imaging
