name: fastspar
owner: bgruening
description: Tool for rapid and scalable correlation estimation for compositional data.
homepage_url: https://github.com/scwatts/fastspar/
long_description: FastSpar is a C++ implementation of the SparCC algorithm for the inference of interaction networks from sparse and compositional data. It rapidly infers correlation networks and calculates P-values using an unbiased estimator.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/fastspar
categories:
  - Metagenomics
  - Statistics