name: replaceColumn
owner: bgruening
description: A tool to replace all column entries of a file given by values of a key-value file. 

long_description: |
  All entries of a column can be replaced by a given value. This value is determined with the key-value principle. 
  This is useful if someone wants to replace e.g. the chromosomes notation in ensembl notation by the ones from UCSC.

categories:
  - Text Manipulation
  
remote_repository_url: https://github.com/joachimwolff/galaxytools/tree/replaceColumn/tools/replaceColumn

auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper to replace column entries: {{ tool_name }}"