name: lissero
owner: bgruening
description: In silico serogroup prediction for Listeria monocytogenes
long_description: |
  In silico serogroup prediction for L. monocytogenes using the lissero tool.
  Predicts serogroups based on alleles lmo1118, lmo0737, ORF2819, ORF2110, and Prs.
homepage_url: https://github.com/MDU-PHL/LisSero
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/lissero
type: unrestricted
categories:
  - Sequence Analysis
