name: 3dtrees_smart_tile
owner: bgruening
description: Subsampling, tiling, merging and matching of (multiple) point clouds.
homepage_url: https://github.com/3dTrees-earth/3Dtrees_smart_tile
long_description: |
  This tool processes 3D point cloud data for tree segmentation by either:
  - Tiling: Subsampling the input point cloud and creating tiles for processing
  - Merging: Merging processed tiles back into the original point cloud resolution
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/3dtrees_smart_tile
type: unrestricted
categories:
- "Geo Science"
