name: cleanlab
owner: bgruening
description: CleanLab is a package to find various types of issues in a dataset.
long_description: |
  CleanLab is a package to find various types of issues in a dataset. By cleanning or replacing the problematice 
  data points, the performance of a machine learning model can be improved.
  This tool is a wrapper around the cleanlab python package.
remote_repository_url: https://github.com/cleanlab/cleanlab
homepage_url: https://cleanlab.ai
type:
categories:
  - Machine Learning
maintainers:
  mjoudy
  anuprulez