name: cleanlab_issue_handler
owner: bgruening
description: Detect and curate data issues using Cleanlab
homepage: https://github.com/cleanlab/cleanlab
remote_repository_url: https://github.com/mjoudy/galaxy-cleanlab