name: graphprot
owner: rnateam
description: GraphProt models binding preferences of RNA-binding proteins.
homepage_url: https://github.com/dmaticzka/GraphProt
long_description: |
  GraphProt is a computational framework for learning sequence- and structure-binding preferences of 
  RNA-binding proteins (RBPs) from high-throughput experimental data such as CLIP-seq data.
  After model training, the learned sequence or structure models can be applied to predict RBP binding 
  profiles on FASTA sequences.
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "{{ tool_name }} from GraphProt framework"
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/rna_tools/graphprot
type: unrestricted
categories:
- Sequence Analysis
- RNA
- CLIP-seq