name: t_coffee
owner: bgruening
description: A collection of tools for Computing, Evaluating and Manipulating Multiple Alignments of DNA, RNA, Protein Sequences and Structures
homepage_url: http://www.tcoffee.org/Projects/tcoffee/index.html
long_description: T-Coffee is a multiple sequence alignment package. You can use T-Coffee to align sequences or to combine the output of your favorite alignment methods (Clustal, Mafft, Probcons, Muscle...) into one unique alignment.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/tcoffee
type: unrestricted
categories:
- Sequence Analysis
