name: sklearn
owner: bgruening
description: Machine Learning tool suite from Scikit-learn

long_description: |
  Scikit-learn is an open source machine learning library written in python.
  It provides different flavors of machine learning algorithms for classification,
  regression, and clustering. It has designed to interoperate with python numerical
  and scientific libraries Numpy and Scipy.
  
  The official repository of Scikit-learn is at https://github.com/scikit-learn/scikit-learn

categories:
  - Machine Learning
  - Statistics
remote_repository_url: https://github.com/bgruening/galaxytools/tools/sklearn

auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for scikit learn tool: {{ tool_name }}"
suite:
  name: "sklearn_suite"
  description: "A suite of Galaxy tools for Machine Learning algorithms such as classification, regression, and clustering"
  
  long_description: |
    Scikit-learn is an open source machine learning library written in python.
    It provides different flavors of machine learning algorithms for classification,
    regression, and clustering. It has designed to interoperate with python numerical
    and scientific libraries Numpy and Scipy.
    
    The official repository of Scikit-learn is at https://github.com/scikit-learn/scikit-learn
