name: split_file_on_column
owner: bgruening
description: Split a file on a specific column.
long_description: |
    Split a file on a specific column.
    Works like group, but every group is saved into a separate file.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/text_processing/split_file_on_column
type: unrestricted
categories:
- Text Manipulation
