name: cutadapt
owner: eggzilla
description: Trim adapters from high-throughput sequencing reads
long_description: |
Cutadapt finds and removes adapter sequences, primers, poly-A tails and other types of unwanted sequence from your high-throughput sequencing reads.
Cleaning your data in this way is often required: Reads from small-RNA sequencing contain the 3’ sequencing adapter because the read is longer than
the molecule that is sequenced. Amplicon reads start with a primer sequence. Poly-A tails are useful for pulling out RNA from your sample, but often
you don’t want them to be in your reads. Cutadapt helps with these trimming tasks by finding the adapter or primer sequences in an error-tolerant way.
It can also modify and filter reads in various ways. Adapter sequences can contain IUPAC wildcard characters.
Also, paired-end reads and even colorspace data is supported. If you want, you can also just demultiplex your input data, without removing adapter sequences at all.

Cutadapt comes with an extensive suite of automated tests and is available under the terms of the MIT license.
homepage_url: https://cutadapt.readthedocs.io/en/stable/
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/cutadapt
type: unrestricted
categories:
- Sequence Analysis
- Fastq Manipulation