categories:
- Computational chemistry
description: Software for docking protein-compound.
long_description: |
    AutoDock Vina is an open-source program for doing molecular docking.
name: autodock_vina
owner: bgruening
remote_repository_url: https://github.com/leobiscassi/galaxytools/tree/autodock_vina_tools/chemicaltoolbox/autodock_vina
type: unrestricted