categories:
  - Web Services
description: stress test a computer system in various selectable ways
long_description: |
  stress-ng will stress test a computer system in various selectable
  ways. It was designed to exercise various physical subsystems of a
  computer as well as the various operating system kernel interfaces.
owner: bgruening-util
remote_repository_url: https://github.com/ColinIanKing/stress-ng
type: unrestricted
name: stress_ng
