categories:
  - System Tools
description: stress test a computer system in various selectable ways
long_description: |
  stress-ng will stress test a computer system in various selectable
  ways. It was designed to exercise various physical subsystems of a
  computer as well as the various operating system kernel interfaces.
owner: bgruening
homepage_url: https://github.com/ColinIanKing/stress-ng
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/stress_ng
type: unrestricted
name: stress_ng
