name: mOTUs
owner: iuc
description: Tool for profiling the abundance of microbial taxa.
homepage_url: https://github.com/motu-tool/mOTUs
long_description:
    mOTUs is a tool designed for profiling the abundance of microbial taxa in metagenomic datasets.
    It can identify and quantify microbial taxa in samples, providing valuable insights into microbial community composition.
    The tool works by analyzing metagenomic reads, offering high-resolution taxonomic profiling, and is particularly useful for microbial ecology studies and microbiome research.
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/mOTUs
categories:
- Metagenomics
- Microbial Ecology
- Taxonomic Profiling
