name: dotprep
owner: bgruening
categories:
- Sequence Analysis
- Assembly
description: "Apply unique anchor filtering to delta files and prepare Dot coordinates"
homepage_url: https://github.com/MariaNattestad/Assemblytics
long_description: |
      This tool takes a delta file from genome alignment tools (such as MUMmer's nucmer), 
      applies Assemblytics unique anchor filtering to identify high-quality alignments, 
      and prepares coordinate input files for visualization with Dot. The unique anchor 
      filtering strategy helps filter out repetitive regions and focuses on reliable 
      anchoring points between sequences by requiring a minimum amount of unique sequence 
      in alignments.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/dotprep
type: unrestricted