categories:
    - Variant Analysis
description: Estimation of tumor cellularity and ploidy
homepage_url: https://cran.r-project.org/web/packages/sequenza
long_description: |
    Sequenza - enables the efficient estimation of tumor cellularity and ploidy,
    and generation of copy number, loss-of-heterozygosity, and mutation frequency pro-files

name: sequenza
owner: bgruening
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/sequenza
type: unrestricted
