name: add_line_to_file
owner: bgruening
description: Adds a text line to the beginning or end of a file.
long_description: |
    Adds a text line to the beginning (as header) or end (as footer) of a file.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/text_processing/add_line_to_file
type: unrestricted
categories:
- Text Manipulation
