name: imagej2_bunwarpj_convert_to_raw
owner: iuc
description: |
  Contains a tool that wraps the bUnwarpJ ImageJ2 plugin, restricting use to the
  "-convert_to_raw" option when running bUnwarpJ from the command line.
homepage_url: http://biocomp.cnb.csic.es/~iarganda/bUnwarpJ/
long_description: |
  Converts an elastic (i.e., B-spline ) transformation file into a raw transformation file.
  The elastic transformation file must be in the same format as the files created with the
  **Save Transformation** option in the **Align two images with bUnwarpJ** tool.
remote_repository_url:
type: unrestricted
categories:
- Imaging
