categories:
- Sequence Analysis
description: Fast all-in-one preprocessing for FastQ files
homepage_url: https://github.com/OpenGene/fastp
long_description: |
  A tool designed to provide fast all-in-one preprocessing for FastQ files. This tool is developed in C++ with multithreading supported to afford high performance.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/fastp
name: fastp
owner: rnateam
type: unrestricted

