name: aresite2
owner: rnateam
description: AREsite2 REST Interface
homepage_url: http://rna.tbi.univie.ac.at/AREsite
long_description: |
  AREsite2 represents an update for AREsite, an on-line resource for the investigation of
  AU-rich elements (ARE) in human and mouse mRNA 3’UTR sequences. The new updated and enhanced
  version allows detailed investigation of AU, GU and U-rich elements (ARE, GRE, URE) in the
  transcriptome of Homo sapiens, Mus musculus, Danio rerio, Caenorhabditis elegans and Drosophila melanogaster.
  It contains information on genomic location, genic context, RNA secondary structure context and conservation
  of annotated motifs. Improvements include annotation of motifs not only in 3’UTRs but in the whole gene
  body including introns, additional genomes, and locally stable secondary structures from genome wide scans.
  Furthermore, we include data from CLIP-Seq experiments in order to highlight motifs with validated protein
  interaction.  Additionally, we provide a REST interface for experienced users to interact with the database
  in an semi-automated manner. The database is publicly available at: http://rna.tbi.univie.ac.at/AREsite
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/rna_tools/aresite2
type: unrestricted
categories:
  - RNA
  - Data Source
  - Sequence Analysis
