categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads version 3.1 of Quast
long_description: |
  Quality Assessment Tool for Genome Assemblies 
  https://github.com/ablab/quast
name: package_quast_3_1
owner: bgruening
type: tool_dependency_definition
