categories:
- Computational chemistry
description: Open Babel is a chemical toolbox designed to speak the many languages of chemical data
long_description: |
  Open Babel is a chemical toolbox designed to speak the many languages of chemical data. It's an open, collaborative project allowing anyone to search, convert, analyze, or store data from molecular modeling, chemistry, solid-state materials, biochemistry, or related areas.

  Home page: https://github.com/openbabel/openbabel
  License: GPL Version 2

auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "{{ tool_name }} tool from Open Babel chemical toolbox"
suite:
  name: suite_openbabel
  description: Open Babel is a chemical toolbox designed to speak the many languages of chemical data. It's an open, collaborative project allowing anyone to search, convert, analyze, or store data from molecular modeling, chemistry, solid-state materials, biochemistry, or related areas.
name: openbabel
owner: bgruening
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/chemicaltoolbox/openbabel
type: unrestricted
