name: miclip
owner: bgruening
description: Identification of binding sites in CLIP-Seq data.
homepage_url: https://cran.r-project.org/src/contrib/Archive/MiClip/
long_description: |
  Identification of binding sites in CLIP-Seq data. https://cran.r-project.org/src/contrib/Archive/MiClip/
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/miclip
type: unrestricted
categories:
- Sequence Analysis
