categories:
- Sequence Analysis
- Next Gen Mappers
description: A tool to deduplicate reads mapped by bismark
long_description: |
    This tool is supposed to remove alignments to the same position in the genome from the Bismark mapping output (both single and paired-end SAM files), which can arise by e.g. excessive PCR amplification.
    If sequences align to the same genomic position but on different strands they will be scored individually.
    http://www.bioinformatics.babraham.ac.uk/projects/bismark/
name: bismark
owner: bgruening
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/bismark/bismark_deduplicate
type: unrestricted