name: tabpfn
owner: bgruening
description: Tabular data prediction using TabPFN using Pytorch.
long_description: |
  The TabPFN is a neural network that learned to do tabular data prediction.
  This is the original CUDA-supporting pytorch impelementation.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/tabpfn
homepage_url: https://github.com/bgruening/galaxytools/tree/master/tools/tabpfn
type:
categories:
  - Machine Learning
maintainers:
  anuprulez
