name: sambamba
owner: bgruening
description: "Sambamba: process your BAM data faster!"
homepage_url: https://github.com/biod/sambamba
long_description: |
    Sambamba is a high performance, highly parallel, robust and fast tool (and library), written in the D programming language, for working with SAM and BAM files. 
remote_repository_url: https://github.com/biod/sambamba
type: unrestricted
categories:
- SAM
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for the sambamba tool suite: {{ tool_name }}"
suite:
  name: "suite_sambamba"
  description: "Sambamba: process your BAM data faster!"
  long_description: |
    Sambamba is a high performance, highly parallel, robust and fast tool  (and library), written in the D programming language, for working with SAM and BAM files.
