categories:
- Sequence Analysis
- RNA
description: Piranha is a peak-caller for CLIP- and RIP-Seq data
long_description: |
  Piranha is a peak-caller for CLIP- and RIP-Seq data. It takes input in BED or BAM format and identifies regions of statistically significant read enrichment.
  Additional covariates may optionally be provided to further inform the peak-calling process. 

  http://smithlabresearch.org/software/piranha/
name: piranha
owner: rnateam
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/piranha
type: unrestricted
