name: tiara
owner: bgruening
description: Tool for identification of eukaryotic sequences in the metagenomic datasets.
homepage_url: https://github.com/ibe-uw/tiara
long_description:
    Tiara is a Deep-learning-based approach for identification of eukaryotic sequences in the metagenomic data.
    It has two-step classification process enables the classification of nuclear and organellar eukaryotic fractions and subsequently divides organellar sequences into plastidial and mitochondrial. 
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/tiara
categories:
  - Metagenomics
  - Sequence Analysis
