name: homer
owner: bgruening
description: Software for motif discovery and next generation sequencing analysis.
homepage_url: http://homer.salk.edu/homer/
long_description: |
 HOMER (Hypergeometric Optimization of Motif EnRichment) is a suite of tools for Motif Discovery 
 and next-gen sequencing analysis.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/homer
type: unrestricted
categories:
- Sequence Analysis
