name: rrna
owner: rnateam
description: Identification of ribosomal RNA genes in metagenomic fragments.
homepage_url: http://weizhong-lab.ucsd.edu/meta_rna/
long_description: Identification of ribosomal RNA genes in metagenomic fragments.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/rRNA
type: unrestricted
categories:
- RNA
