categories:
- Computational chemistry
description: Open Molecule Generator
long_description: |
    Open Molecule Generator - an exhaustive generation of chemical structures 
    Home page: https://sourceforge.net/projects/openmg/
    License: GPL Version 3
homepage_url: https://sourceforge.net/projects/openmg/
name: openmg
owner: bgruening
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/chemicaltoolbox/openmg
type: unrestricted
maintainers:
  - simonbray
