name: data_manager_cons_scores_downloader
owner: bgruening
description: "Download conservation score file"
homepage_url: "https://genome.ucsc.edu/"
long_description: |
    Compatible phastCons and phyloP conservation score files (.bigWig format) can be downloaded from the UCSC, e.g. using the conservation scores obtained from alignments of 99 vertebrate genomes to the human genome
remote_repository_url: "https://github.com/bgruening/galaxytools/tree/master/data_managers/data_manager_cons_scores_downloader"
type: unrestricted
categories:
- Data Managers