categories: 
  - Fasta Manipulation
description: Format CD-hit output to rename representative sequences with cluster name and/or extract distribution inside clusters given a mapping file
name: format_cd_hit_output
owner: bebatut
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/format_cd_hit_output/
