name: footprint
owner: rnateam
description: Find transcription factor footprints
homepage_url: https://ohlerlab.mdc-berlin.de/software/Reproducible_footprinting_139/
long_description: |
  This is a pipeline to find transcription factor footprints
  in ATAC-seq or DNase-seq data.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/footprint
type: unrestricted
categories:
- Sequence Analysis
