name: footprint
owner: rnateam
description: Find transcription factor footprints
homepage_url: TODO
long_description: |
  This is a pipeline to find transcription factor footprints
  in ATAC-seq or DNase-seq data.
remote_repository_url: TODO
type: unrestricted
categories:
- Genomic footprinting
- ATAC-seq
- DNase-seq
