categories:
- RNA
- Sequence Analysis
- Transcriptomics
description: Comprehensive analysis of small RNA sequencing data
homepage_url: https://github.com/mhalushka/miRge3.0
long_description: |
    miRge3.0 is a comprehensive tool for the analysis of small RNA-seq data.
    It performs adapter trimming, read alignment against miRNA reference libraries,
    miRNA quantification, isomiR analysis, A-to-I editing detection, tRNA fragment
    analysis, novel miRNA prediction, UMI processing, and differential expression
    analysis.
name: mirge3
owner: bgruening
remote_repository_url: https://github.com/galaxyproject/bgruening/tree/main/tools/rna_tools/mirge3
type: unrestricted
