categories:
- RNA
description: antaRNA uses ant colony optimization to solve the inverse folding problem in RNA research .
name: antarna
owner: rnateam
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/rna_tools/antarna/
type: unrestricted
