categories:
- RNA
description: antaRNA uses ant colony optimization to solve the inverse folding problem in RNA research.
name: package_antarna_1_1
owner: rnateam
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/rna_tools/antarna/
