categories:
- Sequence Analysis
description: Estimates gene-family founder events 
long_description: |
   GenEra estimates gene-family founder events (i.e., the age of the last common ancestor of 
   protein-coding gene families) through the reimplementation of genomic phylostratigraphy.
name: genera
owner: bgruening
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/genera
homepage_url: https://github.com/josuebarrera/GenEra
type: unrestricted
