categories:
- Assembly
description: Phased error correction and assembly tool for long reads
long_description: |
  PECAT is a phased error correction and assembly pipeline for diploid genomes
  from PacBio CLR, Oxford Nanopore (ONT), or PacBio HiFi long-read data. It
  performs haplotype-aware error correction, phased string-graph assembly, and
  Racon consensus polishing.
name: pecat
owner: iuc
homepage_url: https://github.com/lemene/PECAT
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/pecat
type: unrestricted
