name: targetfinder
owner: rnateam
description: Plant small RNA target prediction tool
homepage_url: https://github.com/carringtonlab/TargetFinder.git
long_description: |
  TargetFinder will computationally predict small RNA binding sites on target transcripts from a sequence database.
  This is done by aligning the input small RNA sequence against all transcripts,
  followed by site scoring using a position-weighted scoring matrix.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/rna_tools/targetfinder/
type: unrestricted
categories:
- RNA
