name: imagej2_make_binary
owner: iuc
description: |
  Contains a tool that wraps the ImageJ2 Make Binary command with options.
homepage_url: http://rsbweb.nih.gov/ij/docs/guide/146-29.html#sub:Make-Binary
long_description: |
  Converts an image into a binary (black and white) image by analyzing the histogram of
  the  entire image and setting an automatic threshold level to create the binary image.
remote_repository_url:
type: unrestricted
categories:
- Imaging
