categories:
- ChIP-seq
- Genome annotation
description: A tool for ChIP peak annotation and visualization
long_description: This wrapper implements the ChIPseeker functions to retrieve the nearest genes around peaks and annotate with genomic region information (Promoter, 5’ UTR, 3’ UTR, Exon, Intron, Downstream, Intergenic, distance to nearest TSS). It also generates some visualisations of the results. It requires a peaks file in BED or interval format and a GTF file to use as the annotation source.
homepage_url: https://bioconductor.org/packages/release/bioc/html/ChIPseeker.html
name: chipseeker
owner: rnateam
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/chipseeker
