categories:
    - Variant Analysis
description: |
    The EDTA package was designed to filter out false discoveries in raw TE candidates and generate a high-quality non-redundant TE library for whole-genome TE annotations. 
long_description: |
    The EDTA package was designed to filter out false discoveries in raw TE candidates and generate a high-quality non-redundant TE library for whole-genome TE annotations. Selection of initial search programs were based on benckmarkings on the annotation performance using a manually curated TE library in the rice genome.
name: edta
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/edta
homepage_url: https://github.com/oushujun/EDTA
type: unrestricted