name: tdrmapper
owner:  bgruening
description: mapping, naming, and quantifying tDRs while annotating and quantifying mismatches and deletions
homepage_url: https://github.com/sararselitsky/tDRmapper
long_description: |
  Small RNA-sequencing has revealed the diversity and high abundance 
  of small RNAs derived from tRNAs, referred to as tRNA-derived RNAs (tDRs).
  tRNA-derived RNAs have unique features that limit the utility of conventional 
  alignment tools and quantification methods. tDRmapper is a tool for mapping, 
  naming, and quantifying tDRs while annotating and quantifying mismatches and deletions.
  tDRmapper was designed specifically for trimmed human small RNA-seq data (single-end, 50x) 
  generated on the Illumina sequencing platform using cDNA libraries that were prepared using 
  the Illumina TruSeq protocol.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/rna_tools/tdrmapper/
type: unrestricted
categories:
- RNA
- Sequence Analysis
