name: confindr
owner: bgruening
description: Detects cross-species contamination in bacterial whole genome assemblies
homepage_url: https://github.com/OLC-Bioinformatics/ConFindr
long_description: |
  ConFindr detects cross-species contamination in bacterial whole genome sequencing data using ribosomal RNA genes. It screens both raw reads and assemblies for foreign rRNA sequences.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/confindr
type: unrestricted
categories:
- Sequence Analysis
