categories:
- Computational chemistry
description: Spectral_hk converts InChIs into spectral hash codes
long_description: |
    Spectral_hk converts InChIs into spectral hash codes. A spectral hash code is a 30-character (150-bit) alphanumeric hash string that uniquely encodes an InChI.
name: spectral_hk
owner: bgruening
homepage_url: https://bitbucket.org/ncgc/spectral_hk/
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/chemicaltoolbox/spectral_hk
type: unrestricted
