name: minipolish
owner: bgruening
categories:
  - Sequence Analysis
description: Polishing miniasm assemblies
homepage_url: https://github.com/rrwick/Minipolish
long_description: |
  minipolish provides the functionalities of Racon, but with some improvements, such as working on GFA files, adding circularising  and rotating circular contigs.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/minipolish
type: unrestricted
