name: fastq_info
owner: bgruening
categories:
- Fastq Manipulation
description:  FASTQ info allows to validate single or paired fastq files
long_description: |
    FASTQ info is a tool for validating single or paired fastq files.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/fastq_info
homepage_url: https://github.com/nunofonseca/fastq_utils
type: unrestricted