name: itsx
owner: bgruening
categories:
  - Metagenomics
description: ITSx is an open source software utility to extract the highly variable ITS1 and ITS2 subregions from ITS sequences.
homepage_url: https://microbiology.se/software/itsx/
long_description: |
  ITSx is an open source software utility to extract the highly variable ITS1 and ITS2 subregions from ITS sequences, 
  which is commonly used as a molecular barcode for e.g. fungi. As the inclusion of parts of the neighbouring, very conserved, 
  ribosomal genes (SSU, 5S and LSU rRNA sequences) in the sequence identification process can lead to severely misleading results, ITSx identifies and extracts only the ITS regions themselves. 
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/itsx
type: unrestricted
