categories: 
  - Metagenomics
  - RNA
description: Reago is tool to assembly 16S ribosomal RNA recovery from metagenomic
  data.
homepage_url: https://github.com/chengyuan/reago-1.1
name: reago
owner: rnateam 
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/rna_tools/reago
