name: plotly_parallel_coordinates_plot
owner: bgruening
description: parallel coordinates plot produced with plotly
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/plotly_parallel_coordinates_plot
homepage_url: "https://plot.ly/python/parallel-coordinates-plot/"
categories:
  - Visualization
long_description: |
  Produce a parallel coordinates plot from a tabular file. Multiple columns are chosen for
  dimensions and a single column for coloring. The plot is buried in a html file which
  provides rich interactive features. Image can be saved in various format, such as 'png', 'svg', 'jpeg' and so on.
