name: rnaformer
owner: ivelet
description: "RNAformer - Prediction of RNA secondary structures"
homepage_url: https://github.com/automl/RNAformer
long_description: |
  RNAformer is a deep learning-based RNA secondary structure prediction model. It currently outputs the predicted secondary structure as a list of base pair positions and the secondary structure in dot-bracket notation, given RNA sequences as either plain text or a FASTA file.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/rna_tools/rnaformer
categories:
  - RNA
auto_tool_repositories:
 name_template: "{{ tool_id }}"
 description_template: "Wrapper for RNAformer inference {{ tool_name }}."
suite:
  name: "suite_rnaformer"
  description: "RNAformer - Prediction of RNA secondary structures"
  long_description: |
    RNAformer is a deep learning-based RNA secondary structure prediction model. It currently outputs the predicted secondary structure as a list of base pair positions and the secondary structure in dot-bracket notation, given RNA sequences as either plain text or a FASTA file.