RNAformer:
  binary_output: true
  cycling: false
  embed_dropout: 0.4
  ff_factor: 4
  ff_kernel: 3
  flash_attn: true
  gating: false
  initializer_range: 0.02
  key_dim_scaler: true
  learn_ln: true
  ln_eps: 1.0e-05
  max_len: 500
  model_dim: 256
  n_layers: 6
  num_head: 4
  pdb_flag: true
  pos_embedding: false
  precision: bf16-mixed
  rel_pos_enc: false
  resi_dropout: 0.4
  rotary_emb: true
  rotary_emb_fraction: 0.5
  seq_vocab_size: 5
  softmax_scale: true
  use_bias: true
  use_glu: false
  zero_init: false
replace_layer:
- attn_pair_row.Wqkv
- attn_pair_row.out_proj
- attn_pair_col.Wqkv
- attn_pair_col.out_proj
- pair_transition.conv1
- pair_transition.conv2
lora: true
r: 32
lora_alpha: 64
lora_dropout: 0.1
