categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads version 3.2.5 of RNAshapes of the RNAShapesStudio.
long_description: |
  RNAshapes is an integrative RNA analysis tool based on the abstract shape approach.
  http://bibiserv.techfak.uni-bielefeld.de/rnashapesstudio
name: package_rnashapes_3_2_5
owner: rnateam
type: tool_dependency_definition
