name: suite_yolo
owner: bgruening
homepage_url: https://github.com/bgruening/galaxytools
categories:
  - Imaging
description: tools for building yolo workflows.
long_description:   a collection of tools for training yolo model.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for yolo {{ tool_name }}."
suite:
  name: "suit_yolo"
  description: "A suite of tools that brings the yolo workflows into Galaxy."
  long_description: |
      a collection of ready-to-use tools for building yolo workflows for image segmentation, tracking etc.
