categories:
- Computational chemistry
description: Align-it is a tool to align molecules according to their pharmacophores.
long_description: |
    Align-it is a tool to align molecules according to their pharmacophores.
    A pharmacophore is an abstract concept based on the specific interactions
    observed in drug-receptor interactions: hydrogen bonding,
    charge transfer, electrostatic and hydrophobic interactions.
    Molecular modeling and/or screening based on pharmacophore similarities
    has been proven to be an important and useful method in drug discovery.
  
    Home page: http://silicos-it.be.s3-website-eu-west-1.amazonaws.com/software/align-it/1.0.4/align-it.html
    License: GPL3+

name: align_it
owner: bgruening
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/chemicaltoolbox/silicos-it/align-it
type: unrestricted
