categories: 
  - Metagenomics 
description: Combine MetaPhlAn2 and HUMAnN2 outputs to relate genus/species abundances and gene families/pathways abundances
name: combine_metaphlan2_humann2 
owner: bgruening
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/combine_metaphlan2_humann2
