categories: [RNA]
description: Second step of GraphClust
long_description: For each fragment of input sequence RNAshapes is used to create a
  set of structures. The default parameters for example consider for each input fragment
  again a window of size 40nt and 150nt with a window shift of 30%. This allows to
  consider local structures as well as global structures for a fragment. From each
  such RNAshape window we take the top 5 shreps (suboptimal structures for the top
  5 shapes) within 20% of the mfe energy of that window and convert them into graphs.
  As shape level (abstraction level) we use 3 for short sequences and 5 for sequences
  >= 80nt. Please see also RNAshapes documentation for all these terms.
name: graphclust_fasta_to_gspan
owner: rnateam
remote_repository_url: https://github.com/eteriSokhoyan/galaxytools/tree/branchForIterations/tools/GraphClust/GSPAN
