name: augustus
owner: bgruening
description: AUGUSTUS is a program that predicts genes in eukaryotic genomic sequences.
homepage_url: http://bioinf.uni-greifswald.de/augustus/
long_description: |
  AUGUSTUS is a program that predicts genes in eukaryotic genomic sequences.

  http://bioinf.uni-greifswald.de/augustus/
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/augustus
type: unrestricted
categories:
- Sequence Analysis
