categories: [RNA]
description: Post-processing. Redundant clusters are merged and instances that belong
  to multiple clusters are assigned unambiguously. For every pair of clusters, the
  relative overlap (i.e. the fraction of instances that occur in both clusters) is
  computed and clusters are merged if the overlap exceeds 50%. instances that occur
  in both clusters) is computed and clusters are merged if the overlap exceeds 50%.
long_description: Post-processing. Redundant clusters are merged and instances that
  belong to multiple clusters are assigned unambiguously. For every pair of clusters,
  the relative overlap (i.e. the fraction of instances that occur in both clusters)
  is computed and clusters are merged if the overlap exceeds 50%. instances that occur
  in both clusters) is computed and clusters are merged if the overlap exceeds 50%.
name: graphclust_postprocessing
owner: rnateam
remote_repository_url: https://github.com/eteriSokhoyan/galaxytools/tree/branchForIterations/tools/GraphClust/CollectResults
