categories:
  - Computational chemistry
description: Access data from online sources
long_description: |
    Contains tools to access data online
      * get_online_data downloads and extracts data from compressed files
      * get_pdb downloads protein structures from the PDB database
name: get_online_data
owner: bgruening
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/chemicaltoolbox/data_source/get_online_data
type: unrestricted
maintainers:
  - simonbray
