name: imagej2
owner: iuc
description: |
  ImageJ2 is a new version of ImageJ for the next generation of multidimensional
  image data, with a focus on scientific imaging.
long_description: |
  ImageJ2 is a new version of ImageJ for the next generation of multidimensional
  image data, with a focus on scientific imaging.  Its central goal is to broaden
  the paradigm of ImageJ beyond the limitations of ImageJ 1.x, to support the next
  generation of multidimensional scientific imaging.

  ImageJ2 is also a collection of reusable software libraries built on the SciJava
  software stack, using a powerful plugin framework to facilitate rapid development
  and painless user customization.

  The Fiji distribution of ImageJ has shipped with beta versions of ImageJ2 for
  quite some time.
categories:
  - Imaging
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/image_processing/imagej2
homepage_url: http://fiji.sc
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for ImageJ2 tool: {{ tool_name }}"
suite:
  name: "suite_imagej2"
  description: |
    "A suite of Galaxy tools for ImageJ2: an environment for working with the next
    generation of multidimensional image data, with a focus on scientific imaging."
  long_description: |
    The ImageJ2 site is located at http://imagej.net/ImageJ2, and the Fiji site is
    at http://fiji.sc.  This ImageJ2 suite currently consists of the following tools.

    imagej2_adjust_threshold_binary - sets lower and upper threshold values,
    segmenting grayscale images into features of interest and background (see
    http://rsbweb.nih.gov/ij/docs/guide/146-28.html).

    imagej2_analyze_particles_binary - analyzes the particles in a segmented
    binary image, providing information about each particle in the image (see
    http://rsbweb.nih.gov/ij/docs/guide/146-29.html).

    imagej2_analyze_skeleton - tags all pixel/voxels in a skeleton image and
    then counts all its junctions, triple and quadruple points and branches,
    and measures their average and maximum length (see
    http://imagejdocu.tudor.lu/doku.php?id=plugin:analysis:analyzeskeleton:start).

    imagej2_binary_to_edm - wraps ImageJ2 EDM plugin, restricting use to the "toEDM"
    method (see https://github.com/imagej/imagej1/blob/master/ij/plugin/filter/EDM.java).

    imagej2_bunwarpj_adapt_transform - wraps the bUnwarpJ ImageJ2 plugin,
    restricting use to the "-adapt_transform" option when running bUnwarpJ
    from the command line (see http://biocomp.cnb.csic.es/~iarganda/bUnwarpJ).

    imagej2_bunwarpj_align - wraps the bUnwarpJ ImageJ2 plugin, restricting use
    to the "-align" option when running bUnwarpJ from the command line (see
    http://biocomp.cnb.csic.es/~iarganda/bUnwarpJ).

    imagej2_bunwarpj_compare_elastic - wraps the bUnwarpJ ImageJ2 plugin,
    restricting use to the "-compare_elastic" option when running bUnwarpJ
    from the command line (see http://biocomp.cnb.csic.es/~iarganda/bUnwarpJ).

    imagej2_bunwarpj_compare_elastic_raw - wraps the bUnwarpJ ImageJ2 plugin,
    restricting use to the "-compare_elastic_raw" option when running bUnwarpJ
    from the command line (see http://biocomp.cnb.csic.es/~iarganda/bUnwarpJ).

    imagej2_bunwarpj_compare_raw - wraps the bUnwarpJ ImageJ2 plugin, restricting
    use to the "-compare_raw" option when running bUnwarpJ from the command line
    (see http://biocomp.cnb.csic.es/~iarganda/bUnwarpJ).

    imagej2_bunwarpj_compose_elastic - wraps the bUnwarpJ ImageJ2 plugin,
    restricting use to the "-compose_elastic" option when running bUnwarpJ
    from the command line (see http://biocomp.cnb.csic.es/~iarganda/bUnwarpJ).

    imagej2_bunwarpj_compose_raw - wraps the bUnwarpJ ImageJ2 plugin,
    restricting use to the "-compose_raw" option when running bUnwarpJ
    from the command line (see http://biocomp.cnb.csic.es/~iarganda/bUnwarpJ).

    imagej2_bunwarpj_compose_raw - wraps the bUnwarpJ ImageJ2 plugin,
    restricting use to the "-compose_raw" option when running bUnwarpJ
    from the command line (see http://biocomp.cnb.csic.es/~iarganda/bUnwarpJ).

    imagej2_bunwarpj_convert_to_raw - wraps the bUnwarpJ ImageJ2 plugin,
    restricting use to the "-convert_to_raw" option when running bUnwarpJ
    from the command line (see http://biocomp.cnb.csic.es/~iarganda/bUnwarpJ).

    imagej2_bunwarpj_elastic_transform - wraps the bUnwarpJ ImageJ2 plugin,
    restricting use to the "-elastic_transform" option when running bUnwarpJ
    from the command line (see http://biocomp.cnb.csic.es/~iarganda/bUnwarpJ).

    imagej2_bunwarpj_raw_transform - wraps the bUnwarpJ ImageJ2 plugin,
    restricting use to the "-raw_transform" option when running bUnwarpJ
    from the command line (see http://biocomp.cnb.csic.es/~iarganda/bUnwarpJ).

    imagej2_create_image - creates a new image of a selected type, size,
    depth and format.

    imagej2_enhance_contrast - enhances image contrast by using either
    normalization (contrast stretching) or histogram equalization.

    imagej2_find_edges - uses a Sobel edge detector to highlight sharp
    changes in intensity in the active image (see
    http://rsb.info.nih.gov/ij/docs/menus/process.html).

    imagej2_find_maxima - wraps the ImageJ2 Find Maxima command (see
    http://rsb.info.nih.gov/ij/docs/menus/process.html).

    imagej2_make_binary - wraps the ImageJ2 Make Binary command with options
    (see http://rsbweb.nih.gov/ij/docs/guide/146-29.html#sub:Make-Binary).

    imagej2_math - Applies a mathematical expression (add, subtract,
    multiply, etc.) to each pixel in the image.

    imagej2_noise - adds specified noise to or removes specified noise
    from and image (see http://fiji.sc/Fiji).

    imagej2_shadows - wraps the various ImageJ2 Shadows commands (East, North,
    Northeast, etc. - see http://rsbweb.nih.gov/ij/docs/guide/146-29.html).

    imagej2_sharpen - wraps the ImageJ2 Sharpen command (see
    http://rsb.info.nih.gov/ij/docs/menus/process.html).

    imagej2_skeletonize3d - finds the centerlines (”skeleton”) of objects
    in the input image (see
    http://imagejdocu.tudor.lu/doku.php?id=plugin:morphology:skeletonize3d:start).

    imagej2_smooth - wraps the ImageJ2 Smooth command (see
    http://rsb.info.nih.gov/ij/docs/menus/process.html).

    imagej2_watershed_binary - wraps the ImageJ2 Watershed command for binary
    images (see http://rsbweb.nih.gov/ij/docs/guide/146-29.html).
