categories:
- Sequence Analysis
- Next Gen Mappers
description: A tool to map bisulfite converted sequence reads and determine cytosine methylation states
long_description: |
    Bismark is a program to map bisulfite treated sequencing reads to a genome of interest and perform methylation calls in a single step. The output can be easily imported into a genome viewer, such as SeqMonk, and enables a researcher to analyse the methylation levels of their samples straight away. It's main features are:

    - Bisulfite mapping and methylation calling in one single step
    - Supports single-end and paired-end read alignments
    - Supports ungapped and gapped alignments
    - Alignment seed length, number of mismatches etc. are adjustable
    - Output discriminates between cytosine methylation in CpG, CHG and CHH context

    http://www.bioinformatics.babraham.ac.uk/projects/bismark/
name: bismark
owner: bgruening
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/bismark
type: unrestricted
