categories:
  - Computational chemistry
description: Access data from the PubChem database
long_description: |
    Access data from the PubChem database
      * get_pubchem_as_smiles downloads all compounds and converts them to the SMILES format
      * get_pubchem_assays downloads PubChem assays and concatenates them
name: get_pubchem
owner: bgruening
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/chemicaltoolbox/data_source/get_pubchem
type: unrestricted
maintainers:
  - simonbray
