name: cellprofiler4
owner: bgruening
categories:
  - Imaging
description: cellProfiler4 wrapper
homepage_url: https://github.com/CellProfiler/CellProfiler
long_description: |
    cellProfiler is free, open-source software for quantitative analysis of biological images
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for cellProfiler moudule {{ tool_name }}."
suite:
  name: "suite_cellprofiler4"
  description: "A suite of tools that brings the cellProfiler project into Galaxy."
  long_description: |
      cellProfiler is free, open-source software for quantitative analysis of biological images
