name: prinseq
owner: bgruening
description: PRINSEQ is a tool that generates summary statistics of sequence and quality data.
homepage_url: http://prinseq.sourceforge.net/manual.html
long_description: |
  PRINSEQ is a tool that generates summary statistics of sequence and quality data and that is 
  used to filter, reformat and trim next-generation sequence data. http://prinseq.sourceforge.net/manual.html
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/prinseq
type: unrestricted
categories:
- Sequence Analysis
