categories:
- BedTools
- RNA
description: unique_regions is a tool for seperating unique regions in .bed files until there is no more overlapping regions
homepage_url: https://github.com/bgruening/galaxytools/tree/master/tools/unique_regions
long_description: |
  unique_regions is a tool for seperating unique regions in .bed files until there is no more overlapping regions. All you need to run unique_regions is a bes file containing the reading regions.
  Then it will create a number of output files containing unique regions without overlapping.
  The number of created files depend on the complexity of overlapping in the origin file.
  If the file contains no overlapping genes, the sole output file should be identical to the input file.

name: unique_regions
owner: bgruening, ramezrawas
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/unique_regions
type: unrestricted
