name: cofold
owner: rnateam
description: Cofold predicts RNA secondary structures that takes co-transcriptional folding into account.
homepage_url: http://www.e-rna.org/cofold/
long_description: Cofold predicts RNA secondary structures that takes co-transcriptional folding into account. http://www.e-rna.org/cofold/
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/rna_tools/cofold
type: unrestricted
categories:
- RNA
