name: hictk
owner: bgruening
homepage_url: https://github.com/paulsengroup/hictk
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/hictk
type: unrestricted
category:
- Convert Formats
- Epigenetics
description: hictk, a blazing-fast toolkit to work with .hic and .cool files
