categories: 
  - Tool Dependency Packages
description: "The GenomeTools genome analysis system is a collection of bioinformatics 
  tools (in the realm of genome informatics) combined into a single binary named 
  gt. It is based on a C library named \u201Clibgenometools\u201D which consists 
  of several modules."
homepage_url: http://genometools.org/
name: package_genometools_1_5_7
owner: rnateam
remote_repository_url: https://github.com/ASaiM/galaxytools/tree/master/packages/package_genometools_1_5_7
