name: tssar
owner: rnateam
description: TSSAR is a Web Service for predicting bacterial Transcription Start Sites from dRNA-seq data.
homepage_url: http://rna.tbi.univie.ac.at/TSSAR
type: unrestricted
categories:
- RNA
