name: hyperparameter_finetune
owner: haibkhn
description: Hyperparameter Search for Finetuning protein sequence classification models
long_description: |
  This tool performs protein sequence classification using a fine-tuned model with LoRA (Low-Rank Adaptation) or DoRA (Dense-to-Rank Adaptation). 
  It supports manual hyperparameter selection or automated hyperparameter search using Optuna. 
  The tool can work with both FASTA and CSV input formats and supports various pre-trained models including ProtT5-XL-UniRef50, ESM-2, and ProtT5-XL-BFD.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/prot_tools
homepage_url: https://github.com/haibkhn/Predict-PTM-site-fine-tuning_Anup
categories:
  - Sequence Analysis
  - Machine Learning
  - Proteomics
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "{{ tool_name }}: {{ tool_description }}"
