name: package_fiji_20141125
owner: iuc
description: Contains a tool dependency definition that downloads and extracts version
  20141125 of Fiji.
homepage_url: http://fiji.sc/Fiji
long_description: |
Fiji is an image processing package. It can be described as a "batteries-included" distribution of ImageJ
(and ImageJ2), bundling Java, Java3D and a lot of plugins organized into a coherent menu structure. Fiji
compares to ImageJ as Ubuntu compares to Linux.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/packages/package_fiji_20141125
type: tool_dependency_definition
categories:
- Tool Dependency Packages
