name: fornac
owner: bgruening
description: A wrapper for fornac

long_description: A galaxy wrapper implementation of the HiCUP-Pipeline from the Bioinformatics Babraham Institute. See http://www.bioinformatics.babraham.ac.uk/projects/hicup/ 

type: unrestricted
categories:
  - Epigenetics
remote_repository_url: https://github.com/Dimitar-92/galaxytools/new/master/tools/fornac
auto_tool_repositories:
  name_template: "fornac_{{ tool_id }}"
  description_template: "Wrapper for the HiCUP suite tool: {{ tool_name }}"
suite:
  name: "suite_hicup"
  description: HiCUP suite to process and analyse HiC data.
long_description: A galaxy wrapper implementation of the HiCUP-Pipeline from the Bioinformatics Babraham Institute. See http://www.bioinformatics.babraham.ac.uk/projects/hicup/ 
