categories:
- Computational chemistry
description: Estimates the drug-likeness of molecules and reports a score
long_description: |
    Estimates the drug-likeness of molecules and reports a score.

    License: GPL3+

name: qed
owner: bgruening
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/chemicaltoolbox/silicos-it/qed
type: unrestricted
