name: imagej2_skeletonize3d
owner: iuc
description: Contains a tool that finds the centerlines (”skeleton”) of objects in the input image.
homepage_url: http://imagejdocu.tudor.lu/doku.php?id=plugin:morphology:skeletonize3d:start
long_description: |
  As Hanno Homman explains in his paper, binary thinning is used for finding the centerlines
  (”skeleton”) of objects in the input image. The general idea is to erode the object’s surface
  iteratively until only the skeleton remains. Erosion has to be performed symmetrically in order
  to the guarantee medial position of the skeleton lines and such that the connectedness of the
  object is preserved. Care has to be taken in order not to create holes or cavities in the object.
remote_repository_url:
type: unrestricted
categories:
- Imaging
