name: ffmpeg
owner: bgruening
description: A complete, cross-platform solution to record, convert and stream audio and video.
long_description: |
    A complete, cross-platform solution to record, convert and stream audio and video.
type: unrestricted
categories:
  - Convert Formats
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/ffmpeg
homepage_url: https://ffmpeg.org
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for the ffmpeg suite tool: {{ tool_name }}"
suite:
  name: "suite_ffmpeg"
  description: A complete, cross-platform solution to record, convert and stream audio and video.
  long_description: A complete, cross-platform solution to record, convert and stream audio and video.
