categories:
- Text Manipulation
description: GNU diff tool that calculates the differences between two files.
homepage_url: http://www.gnu.org/software/diffutils/
long_description: |
  The diff utility is a data comparison tool that calculates and displays the differences between two files. 
  Unlike edit distance notions used for other purposes, diff is line-oriented rather than character-oriented,
  but it is like Levenshtein distance in that it tries to determine the smallest set of deletions and insertions
  to create one file from the other. The diff command displays the changes made in a standard format, such that
  both humans and machines can understand the changes and apply them: given one file and the changes, the other
  file can be created.
name: diff
owner: bgruening
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/diff
type: unrestricted