name: hicup
owner: bgruening
description: A tool for mapping and performing quality control on Hi-C data.

long_description: |
  HiCUP is a tool to process HiC data developed by the Babraham Bioinformatics Institute, Cambridge, UK.

categories:
  - Epigenetics
  
remote_repository_url: https://github.com/joachimwolff/galaxytools/tree/hicup/tools/hicup

auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for HiCUP Pipeline step: {{ tool_name }}"

