categories: [RNA]
description: MLocARNA computes a multiple sequence-structure alignment of RNA sequences.
long_description: MLocARNA computes a multiple sequence-structure alignment of RNA
  sequences. It uses treefile - file with guide tree in NEWICK format. The given
  tree is used as guide tree for the progressive alignment.This saves the calculation
  of pairwise all-vs-all similarities and construction of the guide tree.
name: graphclust_mlocarna
owner: rnateam
remote_repository_url: https://github.com/eteriSokhoyan/galaxytools/tree/branchForIterations/tools/GraphClust/LocARNAGraphClust
