categories:
- RNA
description: Analyze the protein coding potential in MSA
long_description: |
    Predicts protein coding regions in an alignment of homologous
    nucleotide sequences. The prediction is based on evolutionary
    signatures typical for protein genese, i.e. the presence of
    synonyomous/conservative nucleotide mutations, conservation of the
    reading frame and absence of stop codons.
name: rnacode
owner: rnateam
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/rna_tools/rnacode
type: unrestricted
