name: search_protein
owner: bgruening
categories:
- Sequence Analysis
- Metagenomics
description: "Embedding-based protein sequence search using GLM2 and FAISS"
homepage_url: https://github.com/RolandFaure/search_protein
long_description: |
    search_protein is a two-step pipeline for fast, embedding-based protein
    sequence similarity searching.  Query sequences are first converted into
    dense vector representations using the GLM2 language model, then searched
    against a pre-built FAISS index of a reference proteome.  Candidate hits
    are validated and aligned with MMseqs2.  The approach scales sub-linearly
    with the number of queries, making it practical for large-scale metagenomic
    and comparative-proteomics workflows.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/search_proteins
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for the search_protein tool suite: {{ tool_name }}"
suite:
  name: "suite_search_protein"
  description: "Embedding-based protein sequence search using GLM2 and FAISS"
  long_description: |
    search_protein is a two-step pipeline for fast, embedding-based protein
    sequence similarity searching.  Query sequences are first converted into
    dense vector representations using the GLM2 language model, then searched
    against a pre-built FAISS index of a reference proteome.  Candidate hits
    are validated and aligned with MMseqs2.  The approach scales sub-linearly
    with the number of queries, making it practical for large-scale metagenomic
    and comparative-proteomics workflows.