categories:
- Computational chemistry
description: SuCOS is an RDKit-based overlap measure that combines volumetric shape and pharmacophoric features
long_description: |
  SuCOS is an RDKit-based overlap measure that combines volumetric shape and pharmacophoric features
  to give a combined overlap score similar to OpenEye's Tversky Combo and Malhotra and Karanicolas' COS measure.

homepage_url: https://github.com/susanhleung/SuCOS
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "{{ tool_name }} tool from the SuCOS"
suite:
  name: suite_sucos
  description: SuCOS is an RDKit-based overlap measure that combines volumetric shape and pharmacophoric features
name: sucos
owner: bgruening
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/chemicaltoolbox/sucos
type: unrestricted
