name: 3dtrees_metadata
owner: bgruening
description: Extract administrative and ecoregion metadata for 3Dtrees collections.
homepage_url: https://github.com/3dTrees-earth/tool_metadata
long_description: |
  Extracts administrative and ecoregion context for a 3Dtrees collection summary
  by computing the collection centroid from collection_summary.json and
  intersecting it with selected GADM and WWF Terrestrial Ecoregions v2.0 vector
  datasets.
remote_repository_url: https://github.com/3dTrees-earth/galaxytools/tree/3dtrees_metadata_v1_0_0/tools/3dtrees_metadata
type: unrestricted
categories:
- "Geo Science"
