name: dotknot
owner: bgruening
description: DotKnot is a heuristic method for pseudoknot prediction in a given RNA sequence
homepage_url: http://dotknot.csse.uwa.edu.au/
long_description: |
    DotKnot extracts stem regions from the secondary structure probability dot plot calculated by RNAfold. Recursive H-type pseudoknots and intramolecular kissing hairpins are constructed and their presence in the sequence is verified. The detected pseudoknots can then be further analysed using bioinformatics or laboratory techniques.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/rna/dotknot
type: unrestricted
categories:
- RNA
- Proteomics
