name: gfastats
owner: bgruening
categories:
  - Sequence Analysis
description: Tool for generating sequence statistics and simultaneous genome assembly file manipulation.
homepage_url: https://github.com/vgl-hub/gfastats
long_description: |
  gfastats is a single fast and exhaustive tool for summary statistics and simultaneous *fa* (fasta, fastq, gfa [.gz]) genome assembly file manipulation. gfastats also allows seamless fasta<>fastq<>gfa[.gz] conversion.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/gfastats
type: unrestricted
