name: graph_converter
owner: bgruening
description: Convert between different graph formats
homepage_url: 
long_description: Convert between different graph formats
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/graph_converter
type: unrestricted
categories:
- Convert Formats
