name: image_processing
owner: bgruening
description: GraphicsMagick is the swiss army knife of image processing.
homepage_url: http://www.graphicsmagick.org
long_description: Wrapper for simple image processing, like conversion and manipulation. 

remote_repository_url: https://github.com/bgruening/galaxytools/new/gm/tools/image_processing/image_processing/
type: unrestricted
categories:
- Imaging
