name: imagej2_bunwarpj_compose_elastic
owner: iuc
description: |
  Contains a tool that wraps the bUnwarpJ ImageJ2 plugin, restricting use to the
  "-compose_elastic" option when running bUnwarpJ from the command line.
homepage_url: http://biocomp.cnb.csic.es/~iarganda/bUnwarpJ/
long_description: |
  Contains a tool that composes two elastic transformations into a raw transformation.
  The input files must be in the B-spline (i.e., elastic) transformation format (the format
  produced by the Save transformations option of the Align two images with bUnwarpJ tool),
  and the output file will be in "raw" format.
remote_repository_url:
type: unrestricted
categories:
- Imaging
